services:
  postgres:
    ports:
      - "${HOTKEY_POSTGRES_PORT:-5432}:5432"

  redis:
    ports:
      - "${HOTKEY_REDIS_PORT:-6379}:6379"

  minio:
    ports:
      - "${HOTKEY_MINIO_PORT:-9000}:9000"
      - "${HOTKEY_MINIO_CONSOLE_PORT:-9001}:9001"

  db-init:
    env_file:
      - ./backend/.env

  hotkey-server:
    env_file:
      - ./backend/.env
