package database

import (
	"context"
	"slices"
	"testing"
	"time"
)

func TestCanonicalUpgradeDryRunApplyAndRepeatPreserveRows(t *testing.T) {
	runtime := openTestRuntime(t)
	defer func() { _ = runtime.Close() }()
	const email = "canonical-upgrade-preserved@example.test"
	if _, err := runtime.SQL.Exec(userInsertSQL, email, "preserved"); err != nil {
		t.Fatalf("insert pre-upgrade row: %v", err)
	}
	if _, err := runtime.SQL.Exec(`
DROP TABLE derived_artifacts, document_versions, documents,
  source_observation_evidences, source_observations, evidence_snapshots,
  source_rights_decisions, source_rights_decision_batches, source_rights_policies CASCADE`); err != nil {
		t.Fatalf("prepare catalog without evidence lineage: %v", err)
	}

	inspection, err := InspectCanonicalUpgrade(context.Background(), runtime.Pool, CanonicalUpgradeTarget)
	if err != nil {
		t.Fatalf("InspectCanonicalUpgrade(): %v", err)
	}
	if !inspection.CanApply() || !slices.Contains(inspection.MissingTables, "document_versions") || slices.Contains(inspection.CurrentTables, "document_versions") {
		t.Fatalf("dry-run inspection = %#v", inspection)
	}
	if inspection.LockRisk != "access_exclusive_transactional" || inspection.IndexEstimateVersion != "postgres-index-workspace-v1" ||
		inspection.CurrentTableBytes <= 0 || inspection.CurrentIndexBytes <= 0 || inspection.EstimatedIndexWorkspaceBytes <= 0 ||
		len(inspection.Extensions) != 2 {
		t.Fatalf("dry-run capacity and extension evidence = %#v", inspection)
	}
	if _, err := Verify(context.Background(), runtime.Pool); err == nil {
		t.Fatal("catalog without evidence lineage unexpectedly passed target verification")
	}

	first, err := ApplyCanonicalUpgrade(context.Background(), runtime.Pool, CanonicalUpgradeTarget)
	if err != nil {
		t.Fatalf("ApplyCanonicalUpgrade(): %v", err)
	}
	assertUserCount(t, runtime, email, 1)
	second, err := ApplyCanonicalUpgrade(context.Background(), runtime.Pool, CanonicalUpgradeTarget)
	if err != nil {
		t.Fatalf("repeat ApplyCanonicalUpgrade(): %v", err)
	}
	if first.CatalogFingerprint != second.CatalogFingerprint {
		t.Fatalf("repeat upgrade fingerprint changed: %s / %s", first.CatalogFingerprint, second.CatalogFingerprint)
	}
}

func TestCanonicalUpgradeRejectsEmptyAndUnknownTargets(t *testing.T) {
	runtime := openEmptyTestRuntime(t)
	defer func() { _ = runtime.Close() }()
	inspection, err := InspectCanonicalUpgrade(context.Background(), runtime.Pool, CanonicalUpgradeTarget)
	if err != nil {
		t.Fatalf("InspectCanonicalUpgrade(empty): %v", err)
	}
	if inspection.CanApply() || !slices.Contains(inspection.Blockers, "public_schema_empty_use_db_init") {
		t.Fatalf("empty inspection blockers = %v", inspection.Blockers)
	}
	if _, err := ApplyCanonicalUpgrade(context.Background(), runtime.Pool, CanonicalUpgradeTarget); err == nil {
		t.Fatal("empty schema canonical upgrade succeeded")
	}
	if _, err := InspectCanonicalUpgrade(context.Background(), runtime.Pool, "999"); err == nil {
		t.Fatal("unknown canonical upgrade target was accepted")
	}
}

func TestCanonicalUpgradeTreatsHistoricalColumnPositionAsNonSemantic(t *testing.T) {
	runtime := openTestRuntime(t)
	defer func() { _ = runtime.Close() }()
	if _, err := runtime.SQL.Exec(`
DROP TABLE audit_logs;
CREATE TABLE audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_type varchar(32) NOT NULL,
  actor_id bigint,
  action varchar(120) NOT NULL,
  resource_type varchar(64) NOT NULL,
  resource_id bigint,
  request_id varchar(128),
  trace_id varchar(128),
  before_data jsonb,
  after_data jsonb,
  result varchar(16) NOT NULL CHECK (result IN ('success','failure','denied')),
  ip_hash char(64),
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE audit_logs ADD COLUMN idempotency_key varchar(128);
ALTER TABLE audit_logs ADD COLUMN command_fingerprint char(64)`); err != nil {
		t.Fatalf("prepare historical audit column order: %v", err)
	}
	if _, err := ApplyCanonicalUpgrade(context.Background(), runtime.Pool, CanonicalUpgradeTarget); err != nil {
		t.Fatalf("ApplyCanonicalUpgrade() with historical column position: %v", err)
	}
	if _, err := Verify(context.Background(), runtime.Pool); err != nil {
		t.Fatalf("Verify() with historical column position: %v", err)
	}
}

func TestCanonicalUpgradeMakesLegacyContentPublicationTimeNullable(t *testing.T) {
	runtime := openTestRuntime(t)
	defer func() { _ = runtime.Close() }()
	if _, err := runtime.SQL.Exec(`ALTER TABLE contents ALTER COLUMN published_at SET NOT NULL`); err != nil {
		t.Fatalf("prepare legacy contents publication constraint: %v", err)
	}
	if _, err := Verify(context.Background(), runtime.Pool); err == nil {
		t.Fatal("legacy NOT NULL publication time unexpectedly passed target verification")
	}
	if _, err := ApplyCanonicalUpgrade(context.Background(), runtime.Pool, CanonicalUpgradeTarget); err != nil {
		t.Fatalf("ApplyCanonicalUpgrade(): %v", err)
	}
	var nullable string
	if err := runtime.SQL.QueryRow(`SELECT is_nullable FROM information_schema.columns WHERE table_schema='public' AND table_name='contents' AND column_name='published_at'`).Scan(&nullable); err != nil {
		t.Fatalf("read contents publication nullability: %v", err)
	}
	if nullable != "YES" {
		t.Fatalf("contents.published_at is_nullable = %q, want YES", nullable)
	}
}

func TestCanonicalUpgradePreservesLegacyPublishedReport(t *testing.T) {
	runtime := openTestRuntime(t)
	defer func() { _ = runtime.Close() }()
	var actorID int64
	if err := runtime.SQL.QueryRow(`INSERT INTO users (email,password_hash,display_name,role)
VALUES ('legacy-report-upgrade@example.test','hash','legacy report','editor') RETURNING id`).Scan(&actorID); err != nil {
		t.Fatalf("insert legacy report actor: %v", err)
	}
	if _, err := runtime.SQL.Exec(`
DROP TRIGGER report_revision_transition_guard ON reports;
DROP TABLE report_revision_transitions;
ALTER TABLE reports DROP CONSTRAINT reports_status_check;
ALTER TABLE reports DROP COLUMN input_snapshot_hash CASCADE;
ALTER TABLE reports DROP COLUMN submitted_at CASCADE;
ALTER TABLE reports DROP COLUMN submitted_by CASCADE;
ALTER TABLE reports DROP COLUMN reviewed_at CASCADE;
ALTER TABLE reports DROP COLUMN reviewed_by CASCADE;
ALTER TABLE reports DROP COLUMN review_reason CASCADE;
ALTER TABLE reports ADD CONSTRAINT reports_status_check CHECK (status IN ('draft','published','failed','archived'))`); err != nil {
		t.Fatalf("prepare legacy report catalog: %v", err)
	}
	if _, err := runtime.SQL.Exec(`INSERT INTO reports
(id,version,report_type,period_start,period_end,timezone,title,status,version_no,generated_at,published_at,created_by,updated_by)
VALUES (9901,4,'daily',now()-interval '1 day',now(),'UTC','legacy approved','published',1,
        now()-interval '1 hour',now()-interval '30 minutes',$1,$1)`, actorID); err != nil {
		t.Fatalf("insert legacy published report: %v", err)
	}

	if _, err := ApplyCanonicalUpgrade(context.Background(), runtime.Pool, CanonicalUpgradeTarget); err != nil {
		t.Fatalf("ApplyCanonicalUpgrade() legacy published report: %v", err)
	}
	var status, snapshotHash string
	var submittedBy, reviewedBy int64
	var submittedAt, reviewedAt time.Time
	if err := runtime.SQL.QueryRow(`SELECT status,input_snapshot_hash,submitted_at,submitted_by,reviewed_at,reviewed_by
FROM reports WHERE id=9901`).Scan(&status, &snapshotHash, &submittedAt, &submittedBy, &reviewedAt, &reviewedBy); err != nil {
		t.Fatalf("read upgraded legacy report: %v", err)
	}
	if status != "published" || snapshotHash != "0000000000000000000000000000000000000000000000000000000000000000" ||
		submittedAt.IsZero() || reviewedAt.IsZero() || submittedBy != actorID || reviewedBy != actorID {
		t.Fatalf("upgraded legacy report = status %q hash %q submitted %v/%d reviewed %v/%d", status, snapshotHash, submittedAt, submittedBy, reviewedAt, reviewedBy)
	}
}

func TestCanonicalUpgradeConvergesTransitionalEvidenceAndIntentCatalog(t *testing.T) {
	runtime := openTestRuntime(t)
	defer func() { _ = runtime.Close() }()
	if _, err := runtime.SQL.Exec(`
ALTER TABLE monitor_intent_expansion_candidates
  ALTER COLUMN similarity TYPE double precision USING similarity::double precision;
ALTER TABLE monitor_intent_preview_recall_signals
  ALTER COLUMN score TYPE double precision USING score::double precision;
ALTER TABLE monitor_intent_preview_recall_signals
  ADD CONSTRAINT monitor_intent_preview_recall_signals_score_check
  CHECK (score = score AND score NOT IN ('Infinity'::double precision,'-Infinity'::double precision));
ALTER TABLE relevance_evaluation_runs ALTER COLUMN calibration_slope SET DEFAULT 1;
ALTER TABLE relevance_evaluation_runs ALTER COLUMN calibration_intercept SET DEFAULT 0;
DROP INDEX evidence_lineage_reconciliation_items_finding_idx;
DO $fixture$
DECLARE identity_name text;
BEGIN
  SELECT conname INTO identity_name
  FROM pg_constraint
  WHERE conrelid='evidence_lineage_reconciliation_items'::regclass
    AND contype='u'
    AND pg_get_constraintdef(oid,true)='UNIQUE (run_id, scope, asset_type, asset_key_sha256)';
  IF identity_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE evidence_lineage_reconciliation_items DROP CONSTRAINT %I', identity_name);
  END IF;
END
$fixture$;
ALTER TABLE evidence_lineage_reconciliation_items
  ADD CONSTRAINT legacy_reconciliation_identity_uq UNIQUE (run_id,scope,asset_type,asset_id);
CREATE INDEX evidence_lineage_reconciliation_items_finding_idx
  ON evidence_lineage_reconciliation_items(run_id,finding,asset_type,asset_id)`); err != nil {
		t.Fatalf("prepare transitional catalog: %v", err)
	}

	if _, err := ApplyCanonicalUpgrade(context.Background(), runtime.Pool, CanonicalUpgradeTarget); err != nil {
		t.Fatalf("ApplyCanonicalUpgrade() transitional catalog: %v", err)
	}
	if _, err := Verify(context.Background(), runtime.Pool); err != nil {
		t.Fatalf("Verify() transitional catalog: %v", err)
	}
}
