// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/StephenQiu30/hotkey-server/internal/config"
)

// InitializeAPI initializes the API application configuration via Wire.
func InitializeAPI() (config.Config, error) {
	configConfig, err := config.Load()
	if err != nil {
		return config.Config{}, err
	}
	return configConfig, nil
}

// InitializeWorker initializes the Worker application configuration via Wire.
func InitializeWorker() (config.Config, error) {
	configConfig, err := config.Load()
	if err != nil {
		return config.Config{}, err
	}
	return configConfig, nil
}
