// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"net/http"

	"github.com/StephenQiu30/hotkey-server/internal/auth"
	"github.com/StephenQiu30/hotkey-server/internal/config"
	"github.com/StephenQiu30/hotkey-server/internal/content"
	"github.com/StephenQiu30/hotkey-server/internal/monitor"
	"github.com/StephenQiu30/hotkey-server/internal/notify"
	"github.com/StephenQiu30/hotkey-server/internal/server"
	"github.com/StephenQiu30/hotkey-server/internal/topic"
	"github.com/StephenQiu30/hotkey-server/internal/trend"
)

// Injectors from wire.go:

// InitializeAPI creates the API server with all dependencies wired.
func InitializeAPI(cfg config.Config) (http.Handler, error) {
	db, err := provideDB(cfg)
	if err != nil {
		return nil, err
	}
	authRepo := provideAuthRepo(db)
	service := auth.NewService(authRepo)
	handler := auth.NewHandler(service, cfg.JWTSecret)
	monitorRepo := provideMonitorRepo(db)
	monitorService := monitor.NewService(monitorRepo)
	monitorHandler := monitor.NewHandler(monitorService)
	notifyRepo := provideNotifyRepo(db)
	notifyService := notify.NewService(notifyRepo)
	notifyHandler := notify.NewHandler(notifyService)
	postQueryService := providePostQueryService()
	postHandler := content.NewPostHandler(postQueryService)
	topicQueryService := provideTopicQueryService()
	topicHandler := topic.NewTopicHandler(topicQueryService)
	trendQueryService := provideTrendQueryService()
	trendHandler := trend.NewTrendHandler(trendQueryService)
	authMiddleware := provideAuthMiddleware(cfg)
	router := server.NewRouter(server.Dependencies{
		AuthHandler:         handler,
		MonitorHandler:      monitorHandler,
		TopicHandler:        topicHandler,
		TrendHandler:        trendHandler,
		PostHandler:         postHandler,
		NotificationHandler: notifyHandler,
		AuthMiddleware:      authMiddleware,
	})
	return router, nil
}
