CREATE TABLE monitors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(120) NOT NULL,
    description text NOT NULL DEFAULT '',
    status varchar(16) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'active', 'paused', 'archived')),
    languages text[] NOT NULL DEFAULT '{}',
    regions text[] NOT NULL DEFAULT '{}',
    collection_interval_seconds integer NOT NULL DEFAULT 900 CHECK (collection_interval_seconds >= 300),
    relevance_threshold numeric(5,2) NOT NULL DEFAULT 60 CHECK (relevance_threshold BETWEEN 0 AND 100),
    event_threshold numeric(5,2) NOT NULL DEFAULT 70 CHECK (event_threshold BETWEEN 0 AND 100),
    retention_days integer NOT NULL DEFAULT 180 CHECK (retention_days >= 1),
    version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
    created_by bigint NULL REFERENCES users(id) ON DELETE SET NULL,
    updated_by bigint NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz NULL
);
