CREATE TABLE monitor_sources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monitor_id bigint NOT NULL REFERENCES monitors(id) ON DELETE RESTRICT,
    source_connection_id bigint NOT NULL REFERENCES source_connections(id) ON DELETE RESTRICT,
    query_override text NULL,
    source_options jsonb NOT NULL DEFAULT '{}'::jsonb,
    priority smallint NOT NULL DEFAULT 100 CHECK (priority >= 0),
    enabled boolean NOT NULL DEFAULT true,
    version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
    created_by bigint NULL REFERENCES users(id) ON DELETE SET NULL,
    updated_by bigint NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (monitor_id, source_connection_id)
);
