CREATE TABLE monitor_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monitor_id bigint NOT NULL REFERENCES monitors(id) ON DELETE RESTRICT,
    rule_type varchar(24) NOT NULL CHECK (rule_type IN ('keyword', 'phrase', 'exclude_keyword', 'domain', 'author', 'language', 'region', 'entity', 'regex')),
    operator varchar(16) NOT NULL CHECK (operator IN ('contains', 'equals', 'not_equals', 'matches')),
    value text NOT NULL CHECK (length(value) BETWEEN 1 AND 2000),
    weight numeric(5,2) NOT NULL DEFAULT 0 CHECK (weight BETWEEN -100 AND 100),
    priority smallint NOT NULL DEFAULT 100 CHECK (priority >= 0),
    origin varchar(16) NOT NULL DEFAULT 'user' CHECK (origin IN ('user', 'ai', 'system')),
    approval_status varchar(16) NOT NULL DEFAULT 'approved' CHECK (approval_status IN ('pending', 'approved', 'rejected')),
    enabled boolean NOT NULL DEFAULT true,
    version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
    created_by bigint NULL REFERENCES users(id) ON DELETE SET NULL,
    updated_by bigint NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz NULL
);
