CREATE TABLE source_connections (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type varchar(24) NOT NULL CHECK (source_type IN ('rss', 'gdelt', 'reddit', 'hacker_news', 'youtube', 'x')),
    name varchar(120) NOT NULL,
    endpoint text NOT NULL,
    auth_type varchar(24) NOT NULL DEFAULT 'none' CHECK (auth_type IN ('none', 'api_key', 'oauth2', 'bearer')),
    credential_ref text NULL,
    config jsonb NOT NULL DEFAULT '{}'::jsonb,
    enabled boolean NOT NULL DEFAULT true,
    health_status varchar(16) NOT NULL DEFAULT 'unknown' CHECK (health_status IN ('unknown', 'healthy', 'degraded', 'unavailable')),
    terms_policy_url text NULL,
    version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
    created_by bigint NULL REFERENCES users(id) ON DELETE SET NULL,
    updated_by bigint NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz NULL
);
