CREATE TABLE source_checkpoints (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monitor_source_id bigint NOT NULL UNIQUE REFERENCES monitor_sources(id) ON DELETE CASCADE,
    query_hash char(64) NOT NULL,
    cursor_value text NULL,
    etag text NULL,
    last_modified text NULL,
    high_watermark timestamptz NULL,
    next_poll_at timestamptz NOT NULL DEFAULT now(),
    consecutive_failures integer NOT NULL DEFAULT 0 CHECK (consecutive_failures >= 0),
    version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
