CREATE TABLE user_preferences (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    timezone varchar(64) NOT NULL DEFAULT 'Asia/Shanghai',
    locale varchar(16) NOT NULL DEFAULT 'zh-CN',
    preferences jsonb NOT NULL DEFAULT '{}'::jsonb,
    version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
    created_by bigint NULL REFERENCES users(id) ON DELETE SET NULL,
    updated_by bigint NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
