CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(254) NOT NULL,
    password_hash varchar(255) NOT NULL,
    display_name varchar(120) NOT NULL,
    role varchar(16) NOT NULL DEFAULT 'viewer' CHECK (role IN ('admin', 'editor', 'viewer')),
    status varchar(16) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    last_login_at timestamptz NULL,
    version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
    created_by bigint NULL REFERENCES users(id) ON DELETE SET NULL,
    updated_by bigint NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz NULL
);
