package application

import "context"

// SnapshotStore persists an immutable copy before a revision is committed.
// Object keys are generated by the application and are never caller SQL.
type SnapshotStore interface {
	Put(context.Context, string, string) error
}
