// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/hot_event.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/hot_event.go -destination=internal/repository/mock/hot_event.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/StephenQiu30/hotkey-server/internal/model"
	repository "github.com/StephenQiu30/hotkey-server/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockHotEventRepository is a mock of HotEventRepository interface.
type MockHotEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHotEventRepositoryMockRecorder
	isgomock struct{}
}

// MockHotEventRepositoryMockRecorder is the mock recorder for MockHotEventRepository.
type MockHotEventRepositoryMockRecorder struct {
	mock *MockHotEventRepository
}

// NewMockHotEventRepository creates a new mock instance.
func NewMockHotEventRepository(ctrl *gomock.Controller) *MockHotEventRepository {
	mock := &MockHotEventRepository{ctrl: ctrl}
	mock.recorder = &MockHotEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHotEventRepository) EXPECT() *MockHotEventRepositoryMockRecorder {
	return m.recorder
}

// AddPlatform mocks base method.
func (m *MockHotEventRepository) AddPlatform(ctx context.Context, eventID int64, platform *model.EventPlatform) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPlatform", ctx, eventID, platform)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPlatform indicates an expected call of AddPlatform.
func (mr *MockHotEventRepositoryMockRecorder) AddPlatform(ctx, eventID, platform any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPlatform", reflect.TypeOf((*MockHotEventRepository)(nil).AddPlatform), ctx, eventID, platform)
}

// ArchiveOlderThan mocks base method.
func (m *MockHotEventRepository) ArchiveOlderThan(ctx context.Context, cutoff time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveOlderThan", ctx, cutoff)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ArchiveOlderThan indicates an expected call of ArchiveOlderThan.
func (mr *MockHotEventRepositoryMockRecorder) ArchiveOlderThan(ctx, cutoff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveOlderThan", reflect.TypeOf((*MockHotEventRepository)(nil).ArchiveOlderThan), ctx, cutoff)
}

// Create mocks base method.
func (m *MockHotEventRepository) Create(ctx context.Context, event *model.HotEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockHotEventRepositoryMockRecorder) Create(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockHotEventRepository)(nil).Create), ctx, event)
}

// DeleteOlderThan mocks base method.
func (m *MockHotEventRepository) DeleteOlderThan(ctx context.Context, cutoff time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOlderThan", ctx, cutoff)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOlderThan indicates an expected call of DeleteOlderThan.
func (mr *MockHotEventRepositoryMockRecorder) DeleteOlderThan(ctx, cutoff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOlderThan", reflect.TypeOf((*MockHotEventRepository)(nil).DeleteOlderThan), ctx, cutoff)
}

// GetByID mocks base method.
func (m *MockHotEventRepository) GetByID(ctx context.Context, id int64) (*model.HotEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.HotEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockHotEventRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockHotEventRepository)(nil).GetByID), ctx, id)
}

// GetPlatforms mocks base method.
func (m *MockHotEventRepository) GetPlatforms(ctx context.Context, eventID int64) ([]*model.EventPlatform, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlatforms", ctx, eventID)
	ret0, _ := ret[0].([]*model.EventPlatform)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlatforms indicates an expected call of GetPlatforms.
func (mr *MockHotEventRepositoryMockRecorder) GetPlatforms(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlatforms", reflect.TypeOf((*MockHotEventRepository)(nil).GetPlatforms), ctx, eventID)
}

// List mocks base method.
func (m *MockHotEventRepository) List(ctx context.Context, filter repository.HotEventFilter) ([]*model.HotEvent, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*model.HotEvent)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockHotEventRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockHotEventRepository)(nil).List), ctx, filter)
}

// Update mocks base method.
func (m *MockHotEventRepository) Update(ctx context.Context, event *model.HotEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockHotEventRepositoryMockRecorder) Update(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockHotEventRepository)(nil).Update), ctx, event)
}
