// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/notify.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/notify.go -destination=internal/repository/mock/notify.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	model "github.com/StephenQiu30/hotkey-server/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockNotifyRepository is a mock of NotifyRepository interface.
type MockNotifyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotifyRepositoryMockRecorder
	isgomock struct{}
}

// MockNotifyRepositoryMockRecorder is the mock recorder for MockNotifyRepository.
type MockNotifyRepositoryMockRecorder struct {
	mock *MockNotifyRepository
}

// NewMockNotifyRepository creates a new mock instance.
func NewMockNotifyRepository(ctrl *gomock.Controller) *MockNotifyRepository {
	mock := &MockNotifyRepository{ctrl: ctrl}
	mock.recorder = &MockNotifyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifyRepository) EXPECT() *MockNotifyRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNotifyRepository) Create(ctx context.Context, n model.Notification) (model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, n)
	ret0, _ := ret[0].(model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockNotifyRepositoryMockRecorder) Create(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotifyRepository)(nil).Create), ctx, n)
}

// ListUnread mocks base method.
func (m *MockNotifyRepository) ListUnread(ctx context.Context, userID int64) ([]model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnread", ctx, userID)
	ret0, _ := ret[0].([]model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnread indicates an expected call of ListUnread.
func (mr *MockNotifyRepositoryMockRecorder) ListUnread(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnread", reflect.TypeOf((*MockNotifyRepository)(nil).ListUnread), ctx, userID)
}

// MarkRead mocks base method.
func (m *MockNotifyRepository) MarkRead(ctx context.Context, userID, notificationID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRead", ctx, userID, notificationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkRead indicates an expected call of MarkRead.
func (mr *MockNotifyRepositoryMockRecorder) MarkRead(ctx, userID, notificationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRead", reflect.TypeOf((*MockNotifyRepository)(nil).MarkRead), ctx, userID, notificationID)
}
