// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/topic.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/topic.go -destination=internal/repository/mock/topic.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	model "github.com/StephenQiu30/hotkey-server/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockTopicRepository is a mock of TopicRepository interface.
type MockTopicRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTopicRepositoryMockRecorder
	isgomock struct{}
}

// MockTopicRepositoryMockRecorder is the mock recorder for MockTopicRepository.
type MockTopicRepositoryMockRecorder struct {
	mock *MockTopicRepository
}

// NewMockTopicRepository creates a new mock instance.
func NewMockTopicRepository(ctrl *gomock.Controller) *MockTopicRepository {
	mock := &MockTopicRepository{ctrl: ctrl}
	mock.recorder = &MockTopicRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTopicRepository) EXPECT() *MockTopicRepositoryMockRecorder {
	return m.recorder
}

// AddPostToTopic mocks base method.
func (m *MockTopicRepository) AddPostToTopic(ctx context.Context, topicID, postID int64, membershipScore float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPostToTopic", ctx, topicID, postID, membershipScore)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPostToTopic indicates an expected call of AddPostToTopic.
func (mr *MockTopicRepositoryMockRecorder) AddPostToTopic(ctx, topicID, postID, membershipScore any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPostToTopic", reflect.TypeOf((*MockTopicRepository)(nil).AddPostToTopic), ctx, topicID, postID, membershipScore)
}

// GetByID mocks base method.
func (m *MockTopicRepository) GetByID(ctx context.Context, id int64) (*model.TopicSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.TopicSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTopicRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTopicRepository)(nil).GetByID), ctx, id)
}

// ListByMonitor mocks base method.
func (m *MockTopicRepository) ListByMonitor(ctx context.Context, monitorID int64) ([]model.TopicSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByMonitor", ctx, monitorID)
	ret0, _ := ret[0].([]model.TopicSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByMonitor indicates an expected call of ListByMonitor.
func (mr *MockTopicRepositoryMockRecorder) ListByMonitor(ctx, monitorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByMonitor", reflect.TypeOf((*MockTopicRepository)(nil).ListByMonitor), ctx, monitorID)
}

// UpsertTopic mocks base method.
func (m *MockTopicRepository) UpsertTopic(ctx context.Context, monitorID int64, topicKey, title, summary string, heatScore float64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTopic", ctx, monitorID, topicKey, title, summary, heatScore)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertTopic indicates an expected call of UpsertTopic.
func (mr *MockTopicRepositoryMockRecorder) UpsertTopic(ctx, monitorID, topicKey, title, summary, heatScore any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTopic", reflect.TypeOf((*MockTopicRepository)(nil).UpsertTopic), ctx, monitorID, topicKey, title, summary, heatScore)
}
