// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/trend.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/trend.go -destination=internal/repository/mock/trend.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/StephenQiu30/hotkey-server/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockTrendRepository is a mock of TrendRepository interface.
type MockTrendRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTrendRepositoryMockRecorder
	isgomock struct{}
}

// MockTrendRepositoryMockRecorder is the mock recorder for MockTrendRepository.
type MockTrendRepositoryMockRecorder struct {
	mock *MockTrendRepository
}

// NewMockTrendRepository creates a new mock instance.
func NewMockTrendRepository(ctrl *gomock.Controller) *MockTrendRepository {
	mock := &MockTrendRepository{ctrl: ctrl}
	mock.recorder = &MockTrendRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrendRepository) EXPECT() *MockTrendRepositoryMockRecorder {
	return m.recorder
}

// GetMonitorTrends mocks base method.
func (m *MockTrendRepository) GetMonitorTrends(ctx context.Context, monitorID int64, since time.Time) ([]model.MonitorSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMonitorTrends", ctx, monitorID, since)
	ret0, _ := ret[0].([]model.MonitorSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMonitorTrends indicates an expected call of GetMonitorTrends.
func (mr *MockTrendRepositoryMockRecorder) GetMonitorTrends(ctx, monitorID, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMonitorTrends", reflect.TypeOf((*MockTrendRepository)(nil).GetMonitorTrends), ctx, monitorID, since)
}

// GetPreviousTopicHeat mocks base method.
func (m *MockTrendRepository) GetPreviousTopicHeat(ctx context.Context, topicID int64) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreviousTopicHeat", ctx, topicID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPreviousTopicHeat indicates an expected call of GetPreviousTopicHeat.
func (mr *MockTrendRepositoryMockRecorder) GetPreviousTopicHeat(ctx, topicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreviousTopicHeat", reflect.TypeOf((*MockTrendRepository)(nil).GetPreviousTopicHeat), ctx, topicID)
}

// GetTopicTrends mocks base method.
func (m *MockTrendRepository) GetTopicTrends(ctx context.Context, topicID int64, since time.Time) ([]model.TopicSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopicTrends", ctx, topicID, since)
	ret0, _ := ret[0].([]model.TopicSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopicTrends indicates an expected call of GetTopicTrends.
func (mr *MockTrendRepositoryMockRecorder) GetTopicTrends(ctx, topicID, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopicTrends", reflect.TypeOf((*MockTrendRepository)(nil).GetTopicTrends), ctx, topicID, since)
}

// SaveMonitorSnapshot mocks base method.
func (m *MockTrendRepository) SaveMonitorSnapshot(ctx context.Context, snap model.MonitorSnapshot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMonitorSnapshot", ctx, snap)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMonitorSnapshot indicates an expected call of SaveMonitorSnapshot.
func (mr *MockTrendRepositoryMockRecorder) SaveMonitorSnapshot(ctx, snap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMonitorSnapshot", reflect.TypeOf((*MockTrendRepository)(nil).SaveMonitorSnapshot), ctx, snap)
}

// SaveTopicSnapshot mocks base method.
func (m *MockTrendRepository) SaveTopicSnapshot(ctx context.Context, snap model.TopicSnapshot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTopicSnapshot", ctx, snap)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTopicSnapshot indicates an expected call of SaveTopicSnapshot.
func (mr *MockTrendRepositoryMockRecorder) SaveTopicSnapshot(ctx, snap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTopicSnapshot", reflect.TypeOf((*MockTrendRepository)(nil).SaveTopicSnapshot), ctx, snap)
}
