-- HotKey target database schema. This file is the only application-owned
-- database structure fact source and is safe to execute repeatedly on an empty
-- PostgreSQL 16+ database with pgvector installed.

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version bigint NOT NULL DEFAULT 1,
    email varchar(254) NOT NULL,
    password_hash varchar(255) NOT NULL,
    display_name varchar(120) NOT NULL,
    role varchar(16) NOT NULL CHECK (role IN ('admin', 'editor', 'viewer')),
    status varchar(16) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    last_login_at timestamptz,
    created_by bigint, updated_by bigint,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS users_active_email_uq ON users (lower(email)) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS user_preferences (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version bigint NOT NULL DEFAULT 1,
    user_id bigint NOT NULL UNIQUE REFERENCES users(id) ON DELETE RESTRICT,
    timezone varchar(64) NOT NULL DEFAULT 'UTC', locale varchar(16) NOT NULL DEFAULT 'zh-CN',
    preferences jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_by bigint, updated_by bigint,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS source_connections (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version bigint NOT NULL DEFAULT 1,
    source_type varchar(24) NOT NULL CHECK (source_type IN ('rss','gdelt','reddit','hacker_news','youtube','x')),
    name varchar(120) NOT NULL, endpoint text NOT NULL,
    auth_type varchar(24) NOT NULL DEFAULT 'none' CHECK (auth_type IN ('none','api_key','oauth2','bearer')),
    credential_ref text, config jsonb NOT NULL DEFAULT '{}'::jsonb, enabled boolean NOT NULL DEFAULT true,
    health_status varchar(16) NOT NULL DEFAULT 'unknown' CHECK (health_status IN ('unknown','healthy','degraded','unavailable')),
    terms_policy_url text, created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    updated_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS source_connections_active_name_uq ON source_connections(name) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS monitors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version bigint NOT NULL DEFAULT 1,
    name varchar(120) NOT NULL, description text NOT NULL DEFAULT '',
    status varchar(16) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','active','paused','archived')),
    languages text[] NOT NULL DEFAULT '{}', regions text[] NOT NULL DEFAULT '{}',
    collection_interval_seconds integer NOT NULL DEFAULT 300 CHECK (collection_interval_seconds >= 300),
    relevance_threshold numeric(5,2) NOT NULL DEFAULT 0 CHECK (relevance_threshold BETWEEN 0 AND 100),
    event_threshold numeric(5,2) NOT NULL DEFAULT 0 CHECK (event_threshold BETWEEN 0 AND 100),
    retention_days integer NOT NULL DEFAULT 180 CHECK (retention_days >= 1),
    created_by bigint REFERENCES users(id) ON DELETE SET NULL, updated_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS monitors_active_name_uq ON monitors(name) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS monitor_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version bigint NOT NULL DEFAULT 1, monitor_id bigint NOT NULL REFERENCES monitors(id) ON DELETE RESTRICT,
    rule_type varchar(24) NOT NULL CHECK (rule_type IN ('keyword','phrase','exclude_keyword','domain','author','language','region','entity','regex')),
    operator varchar(16) NOT NULL CHECK (operator IN ('contains','equals','not_equals','matches')),
    value text NOT NULL, weight numeric(5,2) NOT NULL DEFAULT 0 CHECK (weight BETWEEN -100 AND 100),
    priority smallint NOT NULL DEFAULT 100, origin varchar(16) NOT NULL DEFAULT 'user' CHECK (origin IN ('user','ai','system')),
    approval_status varchar(16) NOT NULL DEFAULT 'pending' CHECK (approval_status IN ('pending','approved','rejected')),
    enabled boolean NOT NULL DEFAULT true, created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    updated_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS monitor_sources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    monitor_id bigint NOT NULL REFERENCES monitors(id) ON DELETE CASCADE,
    source_connection_id bigint NOT NULL REFERENCES source_connections(id) ON DELETE RESTRICT,
    query_override text, source_options jsonb NOT NULL DEFAULT '{}'::jsonb, priority smallint NOT NULL DEFAULT 100,
    enabled boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (monitor_id, source_connection_id)
);

CREATE TABLE IF NOT EXISTS source_authors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    source_connection_id bigint NOT NULL REFERENCES source_connections(id) ON DELETE RESTRICT,
    external_id varchar(255) NOT NULL, handle varchar(255), display_name varchar(255), profile_url text,
    verified boolean NOT NULL DEFAULT false, follower_count bigint NOT NULL DEFAULT 0 CHECK (follower_count >= 0),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (source_connection_id, external_id)
);

CREATE TABLE IF NOT EXISTS contents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    source_connection_id bigint NOT NULL REFERENCES source_connections(id) ON DELETE RESTRICT,
    external_id varchar(512) NOT NULL, author_id bigint REFERENCES source_authors(id) ON DELETE SET NULL,
    content_type varchar(16) NOT NULL CHECK (content_type IN ('article','post','video','podcast','bulletin')),
    title text NOT NULL DEFAULT '', excerpt text NOT NULL DEFAULT '', canonical_url text NOT NULL,
    language varchar(16) NOT NULL DEFAULT 'und', published_at timestamptz NOT NULL, fetched_at timestamptz NOT NULL,
    dedupe_key char(64) NOT NULL, duplicate_of_id bigint REFERENCES contents(id) ON DELETE SET NULL,
    view_count bigint NOT NULL DEFAULT 0 CHECK (view_count >= 0), like_count bigint NOT NULL DEFAULT 0 CHECK (like_count >= 0),
    comment_count bigint NOT NULL DEFAULT 0 CHECK (comment_count >= 0), share_count bigint NOT NULL DEFAULT 0 CHECK (share_count >= 0),
    extra_metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
    content_status varchar(16) NOT NULL DEFAULT 'active' CHECK (content_status IN ('active','invalid','duplicate','deleted','expired')),
    manual_locked boolean NOT NULL DEFAULT false, created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    updated_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz,
    UNIQUE (source_connection_id, external_id)
);
CREATE INDEX IF NOT EXISTS contents_published_idx ON contents(published_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS contents_source_published_idx ON contents(source_connection_id, published_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS contents_dedupe_key_idx ON contents(dedupe_key);

CREATE TABLE IF NOT EXISTS content_assets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    content_id bigint NOT NULL REFERENCES contents(id) ON DELETE RESTRICT,
    asset_type varchar(24) NOT NULL CHECK (asset_type IN ('raw_response','html','text','image','screenshot','video_metadata','attachment')),
    object_key text NOT NULL UNIQUE, original_url text, mime_type varchar(255) NOT NULL, sha256 char(64) NOT NULL,
    size_bytes bigint NOT NULL DEFAULT 0 CHECK (size_bytes >= 0), captured_at timestamptz NOT NULL,
    object_status varchar(16) NOT NULL DEFAULT 'pending' CHECK (object_status IN ('pending','available','missing','delete_pending','deleted')),
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS monitor_matches (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    monitor_id bigint NOT NULL REFERENCES monitors(id) ON DELETE RESTRICT, content_id bigint NOT NULL REFERENCES contents(id) ON DELETE RESTRICT,
    rule_score numeric(5,2) NOT NULL CHECK (rule_score BETWEEN 0 AND 100), semantic_score numeric(5,2) CHECK (semantic_score BETWEEN 0 AND 100),
    llm_score numeric(5,2) CHECK (llm_score BETWEEN 0 AND 100), final_score numeric(5,2) NOT NULL CHECK (final_score BETWEEN 0 AND 100),
    decision varchar(16) NOT NULL CHECK (decision IN ('accepted','rejected','review')), reason_codes text[] NOT NULL DEFAULT '{}',
    explanation jsonb NOT NULL DEFAULT '{}'::jsonb, algorithm_version varchar(64) NOT NULL, manual_locked boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (monitor_id, content_id)
);
CREATE INDEX IF NOT EXISTS monitor_matches_list_idx ON monitor_matches(monitor_id, decision, final_score DESC, id DESC);

CREATE TABLE IF NOT EXISTS events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    event_key varchar(96) NOT NULL UNIQUE, event_fingerprint char(64), fingerprint_version varchar(64), title_zh text NOT NULL,
    title_en text, summary text NOT NULL DEFAULT '', lifecycle_status varchar(16) NOT NULL CHECK (lifecycle_status IN ('detected','active','cooling','closed','merged','archived','rejected')),
    heat_score numeric(7,2) NOT NULL DEFAULT 0 CHECK (heat_score >= 0), trend_score numeric(7,2) NOT NULL DEFAULT 0,
    confidence numeric(5,2) NOT NULL DEFAULT 0 CHECK (confidence BETWEEN 0 AND 100), first_seen_at timestamptz NOT NULL, last_seen_at timestamptz NOT NULL,
    peak_at timestamptz, representative_content_id bigint REFERENCES contents(id) ON DELETE SET NULL,
    merged_into_id bigint REFERENCES events(id) ON DELETE SET NULL, manual_locked boolean NOT NULL DEFAULT false,
    created_by bigint REFERENCES users(id) ON DELETE SET NULL, updated_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz
);
CREATE INDEX IF NOT EXISTS events_lifecycle_last_seen_idx ON events(lifecycle_status, last_seen_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS event_contents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    event_id bigint NOT NULL REFERENCES events(id) ON DELETE CASCADE, content_id bigint NOT NULL REFERENCES contents(id) ON DELETE RESTRICT,
    membership_score numeric(5,2) NOT NULL CHECK (membership_score BETWEEN 0 AND 100),
    evidence_role varchar(16) NOT NULL CHECK (evidence_role IN ('primary','supporting','context','duplicate')),
    is_representative boolean NOT NULL DEFAULT false, origin varchar(16) NOT NULL CHECK (origin IN ('rule','model','user')),
    manual_locked boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (event_id, content_id)
);
CREATE INDEX IF NOT EXISTS event_contents_score_idx ON event_contents(event_id, membership_score DESC);

CREATE TABLE IF NOT EXISTS monitor_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    monitor_id bigint NOT NULL REFERENCES monitors(id) ON DELETE RESTRICT, event_id bigint NOT NULL REFERENCES events(id) ON DELETE RESTRICT,
    relevance_score numeric(5,2) NOT NULL CHECK (relevance_score BETWEEN 0 AND 100), final_score numeric(7,2) NOT NULL,
    first_matched_at timestamptz NOT NULL, last_matched_at timestamptz NOT NULL,
    status varchar(16) NOT NULL DEFAULT 'visible' CHECK (status IN ('visible','hidden','review')),
    feedback varchar(16) CHECK (feedback IN ('relevant','irrelevant')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (monitor_id, event_id)
);
CREATE INDEX IF NOT EXISTS monitor_events_list_idx ON monitor_events(monitor_id, status, final_score DESC, id DESC);

CREATE TABLE IF NOT EXISTS entities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    entity_key varchar(128) NOT NULL UNIQUE, entity_type varchar(24) NOT NULL CHECK (entity_type IN ('person','organization','product','location','policy','event','other')),
    canonical_name varchar(255) NOT NULL, description text NOT NULL DEFAULT '', status varchar(16) NOT NULL DEFAULT 'active' CHECK (status IN ('active','merged','archived')),
    merged_into_id bigint REFERENCES entities(id) ON DELETE SET NULL, manual_locked boolean NOT NULL DEFAULT false,
    created_by bigint REFERENCES users(id) ON DELETE SET NULL, updated_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS entity_aliases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    entity_id bigint NOT NULL REFERENCES entities(id) ON DELETE CASCADE, alias varchar(255) NOT NULL,
    normalized_alias varchar(255) NOT NULL, language varchar(16) NOT NULL, origin varchar(16) NOT NULL CHECK (origin IN ('source','model','user')),
    confirmed boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (entity_id, normalized_alias, language)
);
CREATE INDEX IF NOT EXISTS entity_aliases_trgm_idx ON entity_aliases USING gin (normalized_alias gin_trgm_ops);

CREATE TABLE IF NOT EXISTS event_entities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    event_id bigint NOT NULL REFERENCES events(id) ON DELETE CASCADE, entity_id bigint NOT NULL REFERENCES entities(id) ON DELETE RESTRICT,
    role varchar(64) NOT NULL, confidence numeric(5,2) NOT NULL CHECK (confidence BETWEEN 0 AND 100),
    origin varchar(16) NOT NULL CHECK (origin IN ('source','model','user')), confirmed boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (event_id, entity_id, role)
);

CREATE TABLE IF NOT EXISTS event_claims (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    event_id bigint NOT NULL REFERENCES events(id) ON DELETE RESTRICT, normalized_claim text NOT NULL, claim_hash char(64) NOT NULL,
    status varchar(24) NOT NULL CHECK (status IN ('unverified','single_source','corroborated','disputed','retracted')),
    confidence numeric(5,2) NOT NULL DEFAULT 0 CHECK (confidence BETWEEN 0 AND 100), first_seen_at timestamptz NOT NULL, last_seen_at timestamptz NOT NULL,
    manual_locked boolean NOT NULL DEFAULT false, created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    updated_by bigint REFERENCES users(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (event_id, claim_hash)
);
CREATE INDEX IF NOT EXISTS event_claims_status_idx ON event_claims(event_id, status);

CREATE TABLE IF NOT EXISTS claim_evidences (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    claim_id bigint NOT NULL REFERENCES event_claims(id) ON DELETE CASCADE, content_id bigint NOT NULL REFERENCES contents(id) ON DELETE RESTRICT,
    stance varchar(16) NOT NULL CHECK (stance IN ('supports','contradicts','mentions')), evidence_locator text NOT NULL,
    short_excerpt varchar(500) NOT NULL DEFAULT '', confidence numeric(5,2) NOT NULL CHECK (confidence BETWEEN 0 AND 100),
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (claim_id, content_id, stance)
);

CREATE TABLE IF NOT EXISTS topics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    topic_key varchar(128) NOT NULL UNIQUE, title varchar(255) NOT NULL, summary text NOT NULL DEFAULT '',
    status varchar(16) NOT NULL DEFAULT 'active' CHECK (status IN ('active','archived','merged')),
    parent_topic_id bigint REFERENCES topics(id) ON DELETE SET NULL, merged_into_id bigint REFERENCES topics(id) ON DELETE SET NULL,
    owner_id bigint REFERENCES users(id) ON DELETE SET NULL, manual_locked boolean NOT NULL DEFAULT false,
    created_by bigint REFERENCES users(id) ON DELETE SET NULL, updated_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS topic_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    topic_id bigint NOT NULL REFERENCES topics(id) ON DELETE CASCADE, event_id bigint NOT NULL REFERENCES events(id) ON DELETE RESTRICT,
    relation_type varchar(16) NOT NULL CHECK (relation_type IN ('evidence_for','milestone','update','contradiction')),
    relevance_score numeric(5,2) NOT NULL CHECK (relevance_score BETWEEN 0 AND 100),
    origin varchar(16) NOT NULL CHECK (origin IN ('rule','model','user')), confirmed boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (topic_id, event_id, relation_type)
);

CREATE TABLE IF NOT EXISTS topic_entities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    topic_id bigint NOT NULL REFERENCES topics(id) ON DELETE CASCADE, entity_id bigint NOT NULL REFERENCES entities(id) ON DELETE RESTRICT,
    relation_type varchar(64) NOT NULL, confidence numeric(5,2) NOT NULL CHECK (confidence BETWEEN 0 AND 100),
    origin varchar(16) NOT NULL CHECK (origin IN ('rule','model','user')), confirmed boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (topic_id, entity_id, relation_type)
);

CREATE TABLE IF NOT EXISTS topic_relations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    from_topic_id bigint NOT NULL REFERENCES topics(id) ON DELETE CASCADE, to_topic_id bigint NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    relation_type varchar(16) NOT NULL CHECK (relation_type IN ('parent_of','related_to','evolves_from','opposes')),
    confidence numeric(5,2) NOT NULL CHECK (confidence BETWEEN 0 AND 100), confirmed boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (from_topic_id <> to_topic_id), UNIQUE (from_topic_id, to_topic_id, relation_type)
);

CREATE TABLE IF NOT EXISTS entity_relations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    from_entity_id bigint NOT NULL REFERENCES entities(id) ON DELETE CASCADE, to_entity_id bigint NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
    relation_type varchar(64) NOT NULL, confidence numeric(5,2) NOT NULL CHECK (confidence BETWEEN 0 AND 100),
    valid_from timestamptz, valid_to timestamptz, origin varchar(16) NOT NULL CHECK (origin IN ('rule','model','user')),
    confirmed boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (from_entity_id <> to_entity_id), CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from),
    UNIQUE NULLS NOT DISTINCT (from_entity_id, to_entity_id, relation_type, valid_from)
);

CREATE TABLE IF NOT EXISTS ai_model_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    name varchar(120) NOT NULL, task_type varchar(24) NOT NULL CHECK (task_type IN ('classification','clustering','extraction','summarization','report','embedding')),
    provider varchar(120) NOT NULL, model_name varchar(255) NOT NULL, endpoint text, credential_ref text,
    parameters jsonb NOT NULL DEFAULT '{}'::jsonb, timeout_seconds integer NOT NULL DEFAULT 30 CHECK (timeout_seconds > 0),
    daily_budget numeric(12,4), fallback_priority smallint NOT NULL DEFAULT 100, enabled boolean NOT NULL DEFAULT true,
    created_by bigint REFERENCES users(id) ON DELETE SET NULL, updated_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS ai_model_profiles_active_name_uq ON ai_model_profiles(name) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    report_type varchar(16) NOT NULL CHECK (report_type IN ('daily','weekly')), monitor_id bigint REFERENCES monitors(id) ON DELETE SET NULL,
    period_start timestamptz NOT NULL, period_end timestamptz NOT NULL, timezone varchar(64) NOT NULL, title text NOT NULL,
    summary text NOT NULL DEFAULT '', body text NOT NULL DEFAULT '', status varchar(16) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','failed','archived')),
    generated_at timestamptz, published_at timestamptz, version_no integer NOT NULL DEFAULT 1 CHECK (version_no > 0),
    created_by bigint REFERENCES users(id) ON DELETE SET NULL, updated_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz,
    CHECK (period_end > period_start)
);
CREATE UNIQUE INDEX IF NOT EXISTS reports_period_version_uq ON reports(report_type, COALESCE(monitor_id, 0), period_start, period_end, version_no);
CREATE INDEX IF NOT EXISTS reports_list_idx ON reports(report_type, monitor_id, period_start DESC, id DESC);

CREATE TABLE IF NOT EXISTS report_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    report_id bigint NOT NULL REFERENCES reports(id) ON DELETE CASCADE, event_id bigint NOT NULL REFERENCES events(id) ON DELETE RESTRICT,
    rank integer NOT NULL CHECK (rank > 0), section varchar(64) NOT NULL, inclusion_reason text NOT NULL DEFAULT '',
    title_snapshot text NOT NULL, summary_snapshot text NOT NULL DEFAULT '', heat_score_snapshot numeric(7,2) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (report_id, event_id), UNIQUE (report_id, rank)
);

CREATE TABLE IF NOT EXISTS report_subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT, monitor_id bigint REFERENCES monitors(id) ON DELETE SET NULL,
    report_type varchar(16) NOT NULL CHECK (report_type IN ('daily','weekly')), channel varchar(16) NOT NULL CHECK (channel IN ('email','rss')),
    recipient varchar(254), rss_token_hash char(64), timezone varchar(64) NOT NULL, schedule varchar(64) NOT NULL,
    enabled boolean NOT NULL DEFAULT true, created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    updated_by bigint REFERENCES users(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz,
    CHECK ((channel = 'email' AND recipient IS NOT NULL AND rss_token_hash IS NULL) OR (channel = 'rss' AND rss_token_hash IS NOT NULL AND recipient IS NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS report_subscriptions_active_scope_uq ON report_subscriptions(user_id, COALESCE(monitor_id, 0), report_type, channel) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS knowledge_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    document_type varchar(16) NOT NULL CHECK (document_type IN ('event','topic','report')),
    event_id bigint REFERENCES events(id) ON DELETE RESTRICT, topic_id bigint REFERENCES topics(id) ON DELETE RESTRICT,
    report_id bigint REFERENCES reports(id) ON DELETE RESTRICT, vault_path text NOT NULL UNIQUE, revision_no bigint NOT NULL DEFAULT 0 CHECK (revision_no >= 0),
    content_hash char(64), generated_hash char(64), status varchar(16) NOT NULL DEFAULT 'planned' CHECK (status IN ('planned','active','conflict','archived','missing')),
    last_written_at timestamptz, created_by bigint REFERENCES users(id) ON DELETE SET NULL, updated_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (num_nonnulls(event_id, topic_id, report_id) = 1)
);

CREATE TABLE IF NOT EXISTS knowledge_change_proposals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    document_id bigint NOT NULL REFERENCES knowledge_documents(id) ON DELETE RESTRICT,
    change_type varchar(16) NOT NULL CHECK (change_type IN ('create','update','merge','archive')),
    base_revision_no bigint NOT NULL CHECK (base_revision_no >= 0), base_hash char(64), proposed_frontmatter jsonb NOT NULL DEFAULT '{}'::jsonb,
    proposed_body text NOT NULL DEFAULT '', diff_summary text NOT NULL DEFAULT '', reason text NOT NULL DEFAULT '',
    status varchar(16) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected','conflict','applied','failed')),
    requested_by bigint REFERENCES users(id) ON DELETE SET NULL, reviewed_by bigint REFERENCES users(id) ON DELETE SET NULL,
    reviewed_at timestamptz, applied_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS knowledge_change_proposals_status_idx ON knowledge_change_proposals(status, created_at, id);

CREATE TABLE IF NOT EXISTS knowledge_annotations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    document_id bigint NOT NULL REFERENCES knowledge_documents(id) ON DELETE RESTRICT, author_id bigint REFERENCES users(id) ON DELETE SET NULL,
    annotation_type varchar(16) NOT NULL CHECK (annotation_type IN ('note','correction','question')), body text NOT NULL,
    status varchar(16) NOT NULL DEFAULT 'active' CHECK (status IN ('active','resolved','archived')),
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS retention_policies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    data_class varchar(64) NOT NULL UNIQUE, retention_days integer NOT NULL CHECK (retention_days > 0),
    action varchar(16) NOT NULL CHECK (action IN ('archive','delete')), enabled boolean NOT NULL DEFAULT true,
    description text NOT NULL DEFAULT '', created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    updated_by bigint REFERENCES users(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS auth_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    family_id uuid NOT NULL UNIQUE, absolute_expires_at timestamptz NOT NULL, last_seen_at timestamptz NOT NULL DEFAULT now(),
    revoked_at timestamptz, revoke_reason varchar(120), created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (absolute_expires_at > created_at)
);
CREATE INDEX IF NOT EXISTS auth_sessions_active_user_idx ON auth_sessions(user_id, absolute_expires_at) WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS auth_refresh_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id bigint NOT NULL REFERENCES auth_sessions(id) ON DELETE CASCADE,
    token_hash char(64) NOT NULL UNIQUE, expires_at timestamptz NOT NULL,
    used_at timestamptz, revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (expires_at > created_at)
);
CREATE INDEX IF NOT EXISTS auth_refresh_tokens_session_expiry_idx ON auth_refresh_tokens(session_id, expires_at);

CREATE TABLE IF NOT EXISTS source_checkpoints (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    monitor_source_id bigint NOT NULL UNIQUE REFERENCES monitor_sources(id) ON DELETE CASCADE, query_hash char(64) NOT NULL,
    cursor_value text, etag text, last_modified text, high_watermark timestamptz, next_poll_at timestamptz NOT NULL,
    consecutive_failures integer NOT NULL DEFAULT 0 CHECK (consecutive_failures >= 0), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS source_checkpoints_poll_idx ON source_checkpoints(next_poll_at, monitor_source_id);

CREATE TABLE IF NOT EXISTS collection_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, monitor_source_id bigint NOT NULL REFERENCES monitor_sources(id) ON DELETE RESTRICT,
    idempotency_key varchar(128) NOT NULL UNIQUE, trigger_type varchar(16) NOT NULL CHECK (trigger_type IN ('schedule','manual','retry','reconcile')),
    scheduled_at timestamptz NOT NULL, started_at timestamptz, finished_at timestamptz,
    status varchar(16) NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','running','succeeded','failed','cancelled')),
    candidate_count bigint NOT NULL DEFAULT 0 CHECK (candidate_count >= 0), accepted_count bigint NOT NULL DEFAULT 0 CHECK (accepted_count >= 0),
    rejected_count bigint NOT NULL DEFAULT 0 CHECK (rejected_count >= 0), error_code varchar(64), created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS collection_run_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, run_id bigint NOT NULL REFERENCES collection_runs(id) ON DELETE CASCADE,
    external_id varchar(512) NOT NULL, payload_hash char(64) NOT NULL, content_id bigint REFERENCES contents(id) ON DELETE SET NULL,
    outcome varchar(16) NOT NULL CHECK (outcome IN ('accepted','rejected','duplicate','failed')), reason_code varchar(64), observed_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (run_id, external_id)
);

CREATE TABLE IF NOT EXISTS content_metric_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, content_id bigint NOT NULL REFERENCES contents(id) ON DELETE RESTRICT,
    captured_at timestamptz NOT NULL, view_count bigint NOT NULL DEFAULT 0 CHECK (view_count >= 0), like_count bigint NOT NULL DEFAULT 0 CHECK (like_count >= 0),
    comment_count bigint NOT NULL DEFAULT 0 CHECK (comment_count >= 0), share_count bigint NOT NULL DEFAULT 0 CHECK (share_count >= 0),
    extra_metrics jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (content_id, captured_at)
);

CREATE TABLE IF NOT EXISTS event_metric_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_id bigint NOT NULL REFERENCES events(id) ON DELETE RESTRICT,
    captured_at timestamptz NOT NULL, heat_score numeric(7,2) NOT NULL CHECK (heat_score >= 0), trend_score numeric(7,2) NOT NULL,
    source_count bigint NOT NULL DEFAULT 0 CHECK (source_count >= 0), content_count bigint NOT NULL DEFAULT 0 CHECK (content_count >= 0),
    created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (event_id, captured_at)
);

CREATE TABLE IF NOT EXISTS ai_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_type varchar(64) NOT NULL, target_type varchar(64) NOT NULL, target_id bigint NOT NULL,
    model_profile_id bigint REFERENCES ai_model_profiles(id) ON DELETE SET NULL, prompt_version varchar(64) NOT NULL, schema_version varchar(64) NOT NULL,
    input_hash char(64) NOT NULL, request_object_key text, response_object_key text, structured_result jsonb NOT NULL DEFAULT '{}'::jsonb,
    tokens bigint NOT NULL DEFAULT 0 CHECK (tokens >= 0), cost numeric(12,4) NOT NULL DEFAULT 0 CHECK (cost >= 0), latency_ms bigint NOT NULL DEFAULT 0 CHECK (latency_ms >= 0),
    status varchar(16) NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','running','succeeded','failed','cancelled')), error text,
    created_at timestamptz NOT NULL DEFAULT now(), started_at timestamptz, finished_at timestamptz,
    UNIQUE (task_type, target_type, target_id, model_profile_id, input_hash, prompt_version)
);

CREATE TABLE IF NOT EXISTS ai_run_evidences (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ai_run_id bigint NOT NULL REFERENCES ai_runs(id) ON DELETE CASCADE,
    content_id bigint NOT NULL REFERENCES contents(id) ON DELETE RESTRICT, evidence_role varchar(32) NOT NULL, position integer NOT NULL DEFAULT 0 CHECK (position >= 0),
    created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (ai_run_id, content_id, evidence_role)
);

CREATE TABLE IF NOT EXISTS content_embeddings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, content_id bigint NOT NULL REFERENCES contents(id) ON DELETE CASCADE,
    model_profile_id bigint NOT NULL REFERENCES ai_model_profiles(id) ON DELETE RESTRICT, model_version varchar(64) NOT NULL, input_hash char(64) NOT NULL,
    embedding halfvec(1024) NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (content_id, model_profile_id, model_version, input_hash)
);
CREATE INDEX IF NOT EXISTS content_embeddings_active_hnsw_idx ON content_embeddings USING hnsw (embedding halfvec_cosine_ops) WHERE active;

CREATE TABLE IF NOT EXISTS monitor_embeddings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, monitor_id bigint NOT NULL REFERENCES monitors(id) ON DELETE CASCADE,
    model_profile_id bigint NOT NULL REFERENCES ai_model_profiles(id) ON DELETE RESTRICT, model_version varchar(64) NOT NULL, input_hash char(64) NOT NULL,
    query_text text NOT NULL, embedding halfvec(1024) NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (monitor_id, model_profile_id, model_version, input_hash)
);
CREATE INDEX IF NOT EXISTS monitor_embeddings_active_hnsw_idx ON monitor_embeddings USING hnsw (embedding halfvec_cosine_ops) WHERE active;

CREATE TABLE IF NOT EXISTS event_embeddings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_id bigint NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    model_profile_id bigint NOT NULL REFERENCES ai_model_profiles(id) ON DELETE RESTRICT, model_version varchar(64) NOT NULL, input_hash char(64) NOT NULL,
    embedding halfvec(1024) NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (event_id, model_profile_id, model_version, input_hash)
);
CREATE INDEX IF NOT EXISTS event_embeddings_active_hnsw_idx ON event_embeddings USING hnsw (embedding halfvec_cosine_ops) WHERE active;

CREATE TABLE IF NOT EXISTS topic_embeddings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, topic_id bigint NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    model_profile_id bigint NOT NULL REFERENCES ai_model_profiles(id) ON DELETE RESTRICT, model_version varchar(64) NOT NULL, input_hash char(64) NOT NULL,
    embedding halfvec(1024) NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (topic_id, model_profile_id, model_version, input_hash)
);
CREATE INDEX IF NOT EXISTS topic_embeddings_active_hnsw_idx ON topic_embeddings USING hnsw (embedding halfvec_cosine_ops) WHERE active;

CREATE TABLE IF NOT EXISTS knowledge_revisions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, document_id bigint NOT NULL REFERENCES knowledge_documents(id) ON DELETE RESTRICT,
    revision_no bigint NOT NULL CHECK (revision_no >= 0), source varchar(16) NOT NULL CHECK (source IN ('user','proposal','reconcile')),
    proposal_id bigint REFERENCES knowledge_change_proposals(id) ON DELETE SET NULL, previous_hash char(64), new_hash char(64),
    snapshot_object_key text, frontmatter_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb, created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (document_id, revision_no)
);

CREATE TABLE IF NOT EXISTS vault_sync_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, run_type varchar(16) NOT NULL CHECK (run_type IN ('full','incremental','reconcile')),
    started_at timestamptz, finished_at timestamptz, status varchar(16) NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','running','succeeded','failed','cancelled')),
    scanned_count bigint NOT NULL DEFAULT 0 CHECK (scanned_count >= 0), changed_count bigint NOT NULL DEFAULT 0 CHECK (changed_count >= 0),
    conflict_count bigint NOT NULL DEFAULT 0 CHECK (conflict_count >= 0), error text, created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS report_deliveries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, report_id bigint NOT NULL REFERENCES reports(id) ON DELETE RESTRICT,
    subscription_id bigint NOT NULL REFERENCES report_subscriptions(id) ON DELETE RESTRICT, idempotency_key varchar(128) NOT NULL UNIQUE,
    status varchar(16) NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','claimed','succeeded','retrying','failed','cancelled')),
    next_attempt_at timestamptz, succeeded_at timestamptz, last_error text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (report_id, subscription_id)
);
CREATE INDEX IF NOT EXISTS report_deliveries_next_attempt_idx ON report_deliveries(status, next_attempt_at, id);

CREATE TABLE IF NOT EXISTS delivery_attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, delivery_id bigint NOT NULL REFERENCES report_deliveries(id) ON DELETE CASCADE,
    attempt_no integer NOT NULL CHECK (attempt_no > 0), started_at timestamptz NOT NULL, finished_at timestamptz,
    status varchar(16) NOT NULL CHECK (status IN ('started','succeeded','failed')), provider_message_id varchar(255), response_code integer, error text,
    created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (delivery_id, attempt_no)
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, actor_type varchar(32) NOT NULL, actor_id bigint,
    action varchar(120) NOT NULL, resource_type varchar(64) NOT NULL, resource_id bigint, request_id varchar(128), trace_id varchar(128),
    before_data jsonb, after_data jsonb, result varchar(16) NOT NULL CHECK (result IN ('success','failure','denied')),
    ip_hash char(64), created_at timestamptz NOT NULL DEFAULT now()
);

-- River job metadata belongs to the job-queue infrastructure and is not exposed
-- through application repositories or public APIs. The runtime integration in
-- PLAN-002 validates its expected River version before workers are enabled.
CREATE TABLE IF NOT EXISTS river_job (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, kind text NOT NULL, args jsonb NOT NULL DEFAULT '{}'::jsonb,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb, state text NOT NULL DEFAULT 'available', attempt integer NOT NULL DEFAULT 0,
    max_attempts integer NOT NULL DEFAULT 25, priority smallint NOT NULL DEFAULT 1, scheduled_at timestamptz NOT NULL DEFAULT now(),
    attempted_at timestamptz, finalized_at timestamptz, unique_key bytea, tags varchar(255)[] NOT NULL DEFAULT '{}',
    errors jsonb[] NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE NULLS NOT DISTINCT (kind, unique_key)
);
CREATE INDEX IF NOT EXISTS river_job_fetch_idx ON river_job(state, scheduled_at, priority, id);

CREATE TABLE IF NOT EXISTS river_job_attempt (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, job_id bigint NOT NULL REFERENCES river_job(id) ON DELETE CASCADE,
    attempt integer NOT NULL, error text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (job_id, attempt)
);

CREATE TABLE IF NOT EXISTS river_queue (
    name text PRIMARY KEY, paused_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS river_leader (
    name text PRIMARY KEY, elected_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS river_migration (
    version bigint PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now()
);
