-- HotKey target database schema. This file is the only application-owned
-- database structure fact source and is safe to execute repeatedly on an empty
-- PostgreSQL 16+ database with pgvector installed.

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version bigint NOT NULL DEFAULT 1,
    email varchar(254) NOT NULL,
    password_hash varchar(255) NOT NULL,
    display_name varchar(120) NOT NULL,
    role varchar(16) NOT NULL CHECK (role IN ('admin', 'editor', 'viewer')),
    status varchar(16) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    last_login_at timestamptz,
    created_by bigint, updated_by bigint,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS users_active_email_uq ON users (lower(email)) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS user_preferences (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version bigint NOT NULL DEFAULT 1,
    user_id bigint NOT NULL UNIQUE REFERENCES users(id) ON DELETE RESTRICT,
    timezone varchar(64) NOT NULL DEFAULT 'UTC', locale varchar(16) NOT NULL DEFAULT 'zh-CN',
    preferences jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_by bigint, updated_by bigint,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS source_connections (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version bigint NOT NULL DEFAULT 1,
    source_type varchar(24) NOT NULL CHECK (source_type IN ('rss','hacker_news')),
    name varchar(120) NOT NULL, endpoint text NOT NULL,
    auth_type varchar(24) NOT NULL DEFAULT 'none' CHECK (auth_type IN ('none','api_key','oauth2','bearer')),
    credential_ref text CHECK ((auth_type = 'none' AND credential_ref IS NULL) OR (auth_type <> 'none' AND credential_ref ~ '^env:[A-Z_][A-Z0-9_]{0,127}$')),
    config jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(config) = 'object'), enabled boolean NOT NULL DEFAULT true,
    health_status varchar(16) NOT NULL DEFAULT 'unknown' CHECK (health_status IN ('unknown','healthy','degraded','unavailable')),
    terms_policy_url text, created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    updated_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS source_connections_active_name_uq ON source_connections(name) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS monitors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version bigint NOT NULL DEFAULT 1,
    name varchar(120) NOT NULL, description text NOT NULL DEFAULT '',
    status varchar(16) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','active','paused','archived')),
    draft_config_version_id bigint, published_config_version_id bigint,
    created_by bigint REFERENCES users(id) ON DELETE SET NULL, updated_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS monitors_active_name_uq ON monitors(lower(name)) WHERE deleted_at IS NULL AND status <> 'archived';

CREATE TABLE IF NOT EXISTS monitor_config_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version bigint NOT NULL DEFAULT 1,
    monitor_id bigint NOT NULL REFERENCES monitors(id) ON DELETE RESTRICT,
    revision bigint NOT NULL CHECK (revision > 0),
    state varchar(16) NOT NULL DEFAULT 'draft' CHECK (state IN ('draft','published','superseded')),
    timezone varchar(64) NOT NULL DEFAULT 'UTC', languages text[] NOT NULL DEFAULT '{}', regions text[] NOT NULL DEFAULT '{}',
    collection_interval_seconds integer NOT NULL DEFAULT 300 CHECK (collection_interval_seconds BETWEEN 300 AND 86400 AND mod(collection_interval_seconds, 60) = 0),
    relevance_threshold numeric(5,2) NOT NULL DEFAULT 60 CHECK (relevance_threshold BETWEEN 60 AND 100),
    event_threshold numeric(5,2) NOT NULL DEFAULT 0 CHECK (event_threshold BETWEEN 0 AND 100),
    retention_days integer NOT NULL DEFAULT 180 CHECK (retention_days BETWEEN 1 AND 3650),
    config_hash char(64), published_at timestamptz,
    created_by bigint REFERENCES users(id) ON DELETE SET NULL, updated_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (monitor_id, revision), UNIQUE (id, monitor_id),
    CHECK (state = 'draft' AND config_hash IS NULL AND published_at IS NULL OR state = ANY (ARRAY['published','superseded']) AND config_hash IS NOT NULL AND published_at IS NOT NULL)
);
CREATE UNIQUE INDEX IF NOT EXISTS monitor_config_versions_one_draft_uq ON monitor_config_versions(monitor_id) WHERE state = 'draft';
CREATE UNIQUE INDEX IF NOT EXISTS monitor_config_versions_one_published_uq ON monitor_config_versions(monitor_id) WHERE state = 'published';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'monitors_draft_config_version_fkey'
          AND conrelid = 'monitors'::regclass
    ) THEN
        ALTER TABLE monitors
            ADD CONSTRAINT monitors_draft_config_version_fkey
            FOREIGN KEY (draft_config_version_id) REFERENCES monitor_config_versions(id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'monitors_published_config_version_fkey'
          AND conrelid = 'monitors'::regclass
    ) THEN
        ALTER TABLE monitors
            ADD CONSTRAINT monitors_published_config_version_fkey
            FOREIGN KEY (published_config_version_id) REFERENCES monitor_config_versions(id) ON DELETE RESTRICT;
    END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS monitor_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version bigint NOT NULL DEFAULT 1, config_version_id bigint NOT NULL REFERENCES monitor_config_versions(id) ON DELETE RESTRICT,
    rule_type varchar(24) NOT NULL CHECK (rule_type IN ('keyword','phrase','exclude_keyword','domain','author','language','region','entity','regex')),
    operator varchar(16) NOT NULL CHECK (operator IN ('contains','equals','not_equals','matches')),
    value text NOT NULL, weight numeric(5,2) NOT NULL DEFAULT 0 CHECK (weight BETWEEN 0 AND 100),
    priority smallint NOT NULL DEFAULT 100, origin varchar(16) NOT NULL DEFAULT 'user' CHECK (origin IN ('user','ai','system')),
    approval_status varchar(16) NOT NULL DEFAULT 'pending' CHECK (approval_status IN ('pending','approved','rejected')),
    enabled boolean NOT NULL DEFAULT true, created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    updated_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS monitor_sources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    config_version_id bigint NOT NULL REFERENCES monitor_config_versions(id) ON DELETE RESTRICT,
    source_connection_id bigint NOT NULL REFERENCES source_connections(id) ON DELETE RESTRICT,
    query_override text CHECK (query_override IS NULL OR (octet_length(query_override) >= 1 AND octet_length(query_override) <= 2048)),
    query_signature char(64), source_options jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (source_options = '{}'::jsonb), priority smallint NOT NULL DEFAULT 100,
    enabled boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (config_version_id, source_connection_id), UNIQUE (id, config_version_id)
);

CREATE OR REPLACE FUNCTION enforce_monitor_config_version_immutability()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.state <> 'draft' OR NEW.config_hash IS NOT NULL OR NEW.published_at IS NOT NULL THEN
            RAISE EXCEPTION USING ERRCODE = '23514', CONSTRAINT = 'monitor_config_versions_initial_draft_check', MESSAGE = 'monitor configuration versions must be created as drafts';
        END IF;
        RETURN NEW;
    END IF;

    IF TG_OP = 'DELETE' THEN
        IF EXISTS (
            SELECT 1
            FROM monitors
            WHERE draft_config_version_id = OLD.id OR published_config_version_id = OLD.id
        ) THEN
            RETURN OLD;
        END IF;
        IF OLD.state <> 'draft' THEN
            RAISE EXCEPTION USING ERRCODE = '23514', CONSTRAINT = 'monitor_config_versions_immutable', MESSAGE = 'published monitor configuration versions are immutable';
        END IF;
        RETURN OLD;
    END IF;

    IF OLD.state = 'superseded' THEN
        RAISE EXCEPTION USING ERRCODE = '23514', CONSTRAINT = 'monitor_config_versions_immutable', MESSAGE = 'superseded monitor configuration versions are immutable';
    END IF;
    IF OLD.state = 'published' THEN
        IF NEW.state <> 'superseded'
           OR NEW.monitor_id IS DISTINCT FROM OLD.monitor_id
           OR NEW.revision IS DISTINCT FROM OLD.revision
           OR NEW.version IS DISTINCT FROM OLD.version
           OR NEW.timezone IS DISTINCT FROM OLD.timezone
           OR NEW.languages IS DISTINCT FROM OLD.languages
           OR NEW.regions IS DISTINCT FROM OLD.regions
           OR NEW.collection_interval_seconds IS DISTINCT FROM OLD.collection_interval_seconds
           OR NEW.relevance_threshold IS DISTINCT FROM OLD.relevance_threshold
           OR NEW.event_threshold IS DISTINCT FROM OLD.event_threshold
           OR NEW.retention_days IS DISTINCT FROM OLD.retention_days
           OR NEW.config_hash IS DISTINCT FROM OLD.config_hash
           OR NEW.published_at IS DISTINCT FROM OLD.published_at
           OR NEW.created_by IS DISTINCT FROM OLD.created_by
           OR NEW.updated_by IS DISTINCT FROM OLD.updated_by
           OR NEW.created_at IS DISTINCT FROM OLD.created_at
           OR NEW.updated_at IS DISTINCT FROM OLD.updated_at THEN
            RAISE EXCEPTION USING ERRCODE = '23514', CONSTRAINT = 'monitor_config_versions_immutable', MESSAGE = 'published monitor configuration versions are immutable';
        END IF;
        RETURN NEW;
    END IF;

    IF NEW.state = 'published' THEN
        IF NEW.config_hash IS NULL OR NEW.published_at IS NULL THEN
            RAISE EXCEPTION USING ERRCODE = '23514', CONSTRAINT = 'monitor_config_versions_publish_check', MESSAGE = 'published monitor configuration requires hash and timestamp';
        END IF;
    ELSIF NEW.state <> 'draft' THEN
        RAISE EXCEPTION USING ERRCODE = '23514', CONSTRAINT = 'monitor_config_versions_state_transition_check', MESSAGE = 'draft configuration must publish before superseding';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS monitor_config_versions_immutable ON monitor_config_versions;
CREATE TRIGGER monitor_config_versions_immutable
BEFORE INSERT OR UPDATE OR DELETE ON monitor_config_versions
FOR EACH ROW EXECUTE FUNCTION enforce_monitor_config_version_immutability();

CREATE OR REPLACE FUNCTION enforce_monitor_config_child_immutability()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    current_config_version_id bigint;
    current_state varchar(16);
    prior_state varchar(16);
BEGIN
    IF TG_OP = 'DELETE' THEN
        current_config_version_id := OLD.config_version_id;
    ELSE
        current_config_version_id := NEW.config_version_id;
    END IF;
    SELECT state INTO current_state FROM monitor_config_versions WHERE id = current_config_version_id;
    IF current_state IS DISTINCT FROM 'draft' THEN
        RAISE EXCEPTION USING ERRCODE = '23514', CONSTRAINT = TG_TABLE_NAME || '_immutable', MESSAGE = 'published monitor configuration children are immutable';
    END IF;
    IF TG_OP = 'UPDATE' AND NEW.config_version_id IS DISTINCT FROM OLD.config_version_id THEN
        SELECT state INTO prior_state FROM monitor_config_versions WHERE id = OLD.config_version_id;
        IF prior_state IS DISTINCT FROM 'draft' THEN
            RAISE EXCEPTION USING ERRCODE = '23514', CONSTRAINT = TG_TABLE_NAME || '_immutable', MESSAGE = 'published monitor configuration children are immutable';
        END IF;
    END IF;
    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

DROP TRIGGER IF EXISTS monitor_rules_immutable ON monitor_rules;
CREATE TRIGGER monitor_rules_immutable
BEFORE INSERT OR UPDATE OR DELETE ON monitor_rules
FOR EACH ROW EXECUTE FUNCTION enforce_monitor_config_child_immutability();

DROP TRIGGER IF EXISTS monitor_sources_immutable ON monitor_sources;
CREATE TRIGGER monitor_sources_immutable
BEFORE INSERT OR UPDATE OR DELETE ON monitor_sources
FOR EACH ROW EXECUTE FUNCTION enforce_monitor_config_child_immutability();

CREATE OR REPLACE FUNCTION enforce_monitor_config_pointers()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    draft_state varchar(16);
    published_state varchar(16);
BEGIN
    IF NEW.draft_config_version_id IS NOT NULL THEN
        SELECT state INTO draft_state FROM monitor_config_versions WHERE id = NEW.draft_config_version_id AND monitor_id = NEW.id;
        IF draft_state IS DISTINCT FROM 'draft' THEN
            RAISE EXCEPTION USING ERRCODE = '23514', CONSTRAINT = 'monitors_draft_config_version_owner_check', MESSAGE = 'draft configuration does not belong to monitor or is not a draft';
        END IF;
    END IF;
    IF NEW.published_config_version_id IS NOT NULL THEN
        SELECT state INTO published_state FROM monitor_config_versions WHERE id = NEW.published_config_version_id AND monitor_id = NEW.id;
        IF published_state IS DISTINCT FROM 'published' THEN
            RAISE EXCEPTION USING ERRCODE = '23514', CONSTRAINT = 'monitors_published_config_version_owner_check', MESSAGE = 'published configuration does not belong to monitor or is not published';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS monitors_config_pointer_owner ON monitors;
CREATE TRIGGER monitors_config_pointer_owner
BEFORE INSERT OR UPDATE OF draft_config_version_id, published_config_version_id ON monitors
FOR EACH ROW EXECUTE FUNCTION enforce_monitor_config_pointers();

CREATE OR REPLACE FUNCTION validate_source_connection_configuration()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    config_key text;
BEGIN
    IF jsonb_typeof(NEW.config) <> 'object' THEN
        RAISE EXCEPTION USING ERRCODE = '23514', CONSTRAINT = 'source_connections_config_object_check', MESSAGE = 'source config must be an object';
    END IF;
    FOR config_key IN SELECT jsonb_object_keys(NEW.config)
    LOOP
        IF config_key NOT IN ('allow_body_storage', 'requires_attribution', 'requires_deletion_sync', 'content_retention_days', 'metrics_retention_days', 'allowed_languages', 'allowed_regions', 'rate_limit_per_minute', 'request_timeout_seconds', 'max_pages_per_run') THEN
            RAISE EXCEPTION USING ERRCODE = '23514', CONSTRAINT = 'source_connections_config_whitelist_check', MESSAGE = 'source config contains an unsupported key';
        END IF;
    END LOOP;
    IF (NEW.config ? 'allow_body_storage' AND jsonb_typeof(NEW.config->'allow_body_storage') <> 'boolean')
       OR (NEW.config ? 'requires_attribution' AND jsonb_typeof(NEW.config->'requires_attribution') <> 'boolean')
       OR (NEW.config ? 'requires_deletion_sync' AND jsonb_typeof(NEW.config->'requires_deletion_sync') <> 'boolean') THEN
        RAISE EXCEPTION USING ERRCODE = '23514', CONSTRAINT = 'source_connections_config_boolean_check', MESSAGE = 'source config boolean value is invalid';
    END IF;
    IF (NEW.config ? 'content_retention_days' AND (jsonb_typeof(NEW.config->'content_retention_days') <> 'number' OR (NEW.config->>'content_retention_days')::numeric <> trunc((NEW.config->>'content_retention_days')::numeric) OR (NEW.config->>'content_retention_days')::integer NOT BETWEEN 1 AND 3650))
       OR (NEW.config ? 'metrics_retention_days' AND (jsonb_typeof(NEW.config->'metrics_retention_days') <> 'number' OR (NEW.config->>'metrics_retention_days')::numeric <> trunc((NEW.config->>'metrics_retention_days')::numeric) OR (NEW.config->>'metrics_retention_days')::integer NOT BETWEEN 1 AND 3650))
       OR (NEW.config ? 'rate_limit_per_minute' AND (jsonb_typeof(NEW.config->'rate_limit_per_minute') <> 'number' OR (NEW.config->>'rate_limit_per_minute')::numeric <> trunc((NEW.config->>'rate_limit_per_minute')::numeric) OR (NEW.config->>'rate_limit_per_minute')::integer NOT BETWEEN 1 AND 600))
       OR (NEW.config ? 'request_timeout_seconds' AND (jsonb_typeof(NEW.config->'request_timeout_seconds') <> 'number' OR (NEW.config->>'request_timeout_seconds')::numeric <> trunc((NEW.config->>'request_timeout_seconds')::numeric) OR (NEW.config->>'request_timeout_seconds')::integer NOT BETWEEN 1 AND 120))
       OR (NEW.config ? 'max_pages_per_run' AND (jsonb_typeof(NEW.config->'max_pages_per_run') <> 'number' OR (NEW.config->>'max_pages_per_run')::numeric <> trunc((NEW.config->>'max_pages_per_run')::numeric) OR (NEW.config->>'max_pages_per_run')::integer NOT BETWEEN 1 AND 20)) THEN
        RAISE EXCEPTION USING ERRCODE = '23514', CONSTRAINT = 'source_connections_config_integer_check', MESSAGE = 'source config integer value is invalid';
    END IF;
    IF (NEW.config ? 'allowed_languages' AND (jsonb_typeof(NEW.config->'allowed_languages') <> 'array' OR jsonb_array_length(NEW.config->'allowed_languages') > 8 OR EXISTS (SELECT 1 FROM jsonb_array_elements(NEW.config->'allowed_languages') AS value WHERE jsonb_typeof(value) <> 'string')))
       OR (NEW.config ? 'allowed_regions' AND (jsonb_typeof(NEW.config->'allowed_regions') <> 'array' OR jsonb_array_length(NEW.config->'allowed_regions') > 8 OR EXISTS (SELECT 1 FROM jsonb_array_elements(NEW.config->'allowed_regions') AS value WHERE jsonb_typeof(value) <> 'string'))) THEN
        RAISE EXCEPTION USING ERRCODE = '23514', CONSTRAINT = 'source_connections_config_array_check', MESSAGE = 'source config array value is invalid';
    END IF;
    IF NEW.source_type = 'hacker_news' AND NEW.endpoint <> 'https://hacker-news.firebaseio.com/v0' THEN
        RAISE EXCEPTION USING ERRCODE = '23514', CONSTRAINT = 'source_connections_hacker_news_endpoint_check', MESSAGE = 'hacker news endpoint must be the official endpoint';
    END IF;
    IF TG_OP = 'UPDATE'
       AND (NEW.source_type IS DISTINCT FROM OLD.source_type OR NEW.endpoint IS DISTINCT FROM OLD.endpoint OR NEW.config IS DISTINCT FROM OLD.config)
       AND EXISTS (
           SELECT 1
           FROM monitor_sources AS monitor_source
           JOIN monitor_config_versions AS config_version ON config_version.id = monitor_source.config_version_id
           WHERE monitor_source.source_connection_id = OLD.id AND config_version.state IN ('published', 'superseded')
       ) THEN
        RAISE EXCEPTION USING ERRCODE = '23514', CONSTRAINT = 'source_connections_semantic_immutable', MESSAGE = 'published monitor configuration source semantics are immutable';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS source_connections_semantic_immutable ON source_connections;
CREATE TRIGGER source_connections_semantic_immutable
BEFORE INSERT OR UPDATE OF source_type, endpoint, config ON source_connections
FOR EACH ROW EXECUTE FUNCTION validate_source_connection_configuration();

CREATE TABLE IF NOT EXISTS source_authors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    source_connection_id bigint NOT NULL REFERENCES source_connections(id) ON DELETE RESTRICT,
    external_id varchar(255) NOT NULL, handle varchar(255), display_name varchar(255), profile_url text,
    verified boolean NOT NULL DEFAULT false, follower_count bigint NOT NULL DEFAULT 0 CHECK (follower_count >= 0),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (source_connection_id, external_id)
);

CREATE TABLE IF NOT EXISTS contents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    source_connection_id bigint NOT NULL REFERENCES source_connections(id) ON DELETE RESTRICT,
    external_id varchar(512) NOT NULL, author_id bigint REFERENCES source_authors(id) ON DELETE SET NULL,
    content_type varchar(16) NOT NULL CHECK (content_type IN ('article','post','video','podcast','bulletin')),
    title text NOT NULL DEFAULT '', excerpt text NOT NULL DEFAULT '', canonical_url text NOT NULL,
    language varchar(16) NOT NULL DEFAULT 'und', published_at timestamptz NOT NULL, fetched_at timestamptz NOT NULL,
    dedupe_key char(64) NOT NULL, duplicate_of_id bigint REFERENCES contents(id) ON DELETE SET NULL,
    view_count bigint CHECK (view_count >= 0), like_count bigint CHECK (like_count >= 0),
    comment_count bigint CHECK (comment_count >= 0), share_count bigint CHECK (share_count >= 0),
    extra_metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
    content_status varchar(16) NOT NULL DEFAULT 'active' CHECK (content_status IN ('active','invalid','duplicate','deleted','expired')),
    manual_locked boolean NOT NULL DEFAULT false, created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    updated_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz,
    dedupe_reason varchar(32), dedupe_version varchar(64),
    UNIQUE (source_connection_id, external_id),
    UNIQUE (id, source_connection_id),
    CHECK ((content_status = 'duplicate' AND duplicate_of_id IS NOT NULL AND dedupe_reason IS NOT NULL AND dedupe_version IS NOT NULL)
        OR (content_status <> 'duplicate' AND duplicate_of_id IS NULL AND dedupe_reason IS NULL AND dedupe_version IS NULL))
);
CREATE INDEX IF NOT EXISTS contents_published_idx ON contents(published_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS contents_source_published_idx ON contents(source_connection_id, published_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS contents_dedupe_key_idx ON contents(dedupe_key);

CREATE TABLE IF NOT EXISTS content_assets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    content_id bigint NOT NULL REFERENCES contents(id) ON DELETE RESTRICT,
    asset_type varchar(24) NOT NULL CHECK (asset_type IN ('raw_response','html','text','image','screenshot','video_metadata','attachment')),
    object_key text NOT NULL UNIQUE, original_url text, mime_type varchar(255) NOT NULL, sha256 char(64) NOT NULL,
    size_bytes bigint NOT NULL DEFAULT 0 CHECK (size_bytes >= 0), captured_at timestamptz NOT NULL,
    object_status varchar(16) NOT NULL DEFAULT 'pending' CHECK (object_status IN ('pending','available','missing','delete_pending','deleted')),
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS monitor_matches (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    monitor_id bigint NOT NULL, monitor_config_version_id bigint NOT NULL, content_id bigint NOT NULL REFERENCES contents(id) ON DELETE RESTRICT,
    rule_score numeric(5,2) NOT NULL CHECK (rule_score BETWEEN 0 AND 100), semantic_score numeric(5,2) CHECK (semantic_score BETWEEN 0 AND 100),
    llm_score numeric(5,2) CHECK (llm_score BETWEEN 0 AND 100), final_score numeric(5,2) NOT NULL CHECK (final_score BETWEEN 0 AND 100),
    decision varchar(16) NOT NULL CHECK (decision IN ('accepted','rejected','review')), reason_codes text[] NOT NULL DEFAULT '{}',
    explanation jsonb NOT NULL DEFAULT '{}'::jsonb, algorithm_version varchar(64) NOT NULL, manual_locked boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (monitor_config_version_id, monitor_id) REFERENCES monitor_config_versions(id, monitor_id) ON DELETE RESTRICT,
    UNIQUE (monitor_config_version_id, content_id)
);
CREATE INDEX IF NOT EXISTS monitor_matches_list_idx ON monitor_matches(monitor_config_version_id, decision, final_score DESC, id DESC);

CREATE TABLE IF NOT EXISTS events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    event_key varchar(96) NOT NULL UNIQUE, event_fingerprint char(64), fingerprint_version varchar(64), title_zh text NOT NULL,
    title_en text, summary text NOT NULL DEFAULT '', lifecycle_status varchar(16) NOT NULL CHECK (lifecycle_status IN ('detected','active','cooling','closed','merged','archived','rejected')),
    heat_score numeric(7,2) NOT NULL DEFAULT 0 CHECK (heat_score >= 0), trend_score numeric(7,2) NOT NULL DEFAULT 0,
    confidence numeric(5,2) NOT NULL DEFAULT 0 CHECK (confidence BETWEEN 0 AND 100), first_seen_at timestamptz NOT NULL, last_seen_at timestamptz NOT NULL,
    peak_at timestamptz, representative_content_id bigint REFERENCES contents(id) ON DELETE SET NULL,
    merged_into_id bigint REFERENCES events(id) ON DELETE SET NULL, manual_locked boolean NOT NULL DEFAULT false,
    created_by bigint REFERENCES users(id) ON DELETE SET NULL, updated_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz
);
CREATE INDEX IF NOT EXISTS events_lifecycle_last_seen_idx ON events(lifecycle_status, last_seen_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS event_contents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    event_id bigint NOT NULL REFERENCES events(id) ON DELETE CASCADE, content_id bigint NOT NULL REFERENCES contents(id) ON DELETE RESTRICT,
    membership_score numeric(5,2) NOT NULL CHECK (membership_score BETWEEN 0 AND 100),
    evidence_role varchar(16) NOT NULL CHECK (evidence_role IN ('primary','supporting','context','duplicate')),
    is_representative boolean NOT NULL DEFAULT false, origin varchar(16) NOT NULL CHECK (origin IN ('rule','model','user')),
    manual_locked boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (event_id, content_id)
);
CREATE INDEX IF NOT EXISTS event_contents_score_idx ON event_contents(event_id, membership_score DESC);

CREATE TABLE IF NOT EXISTS monitor_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    monitor_id bigint NOT NULL REFERENCES monitors(id) ON DELETE RESTRICT, event_id bigint NOT NULL REFERENCES events(id) ON DELETE RESTRICT,
    relevance_score numeric(5,2) NOT NULL CHECK (relevance_score BETWEEN 0 AND 100), final_score numeric(7,2) NOT NULL,
    first_matched_at timestamptz NOT NULL, last_matched_at timestamptz NOT NULL,
    status varchar(16) NOT NULL DEFAULT 'visible' CHECK (status IN ('visible','hidden','review')),
    feedback varchar(16) CHECK (feedback IN ('relevant','irrelevant')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (monitor_id, event_id)
);
CREATE INDEX IF NOT EXISTS monitor_events_list_idx ON monitor_events(monitor_id, status, final_score DESC, id DESC);

CREATE TABLE IF NOT EXISTS entities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    entity_key varchar(128) NOT NULL UNIQUE, entity_type varchar(24) NOT NULL CHECK (entity_type IN ('person','organization','product','location','policy','event','other')),
    canonical_name varchar(255) NOT NULL, description text NOT NULL DEFAULT '', status varchar(16) NOT NULL DEFAULT 'active' CHECK (status IN ('active','merged','archived')),
    merged_into_id bigint REFERENCES entities(id) ON DELETE SET NULL, manual_locked boolean NOT NULL DEFAULT false,
    created_by bigint REFERENCES users(id) ON DELETE SET NULL, updated_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS entity_aliases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    entity_id bigint NOT NULL REFERENCES entities(id) ON DELETE CASCADE, alias varchar(255) NOT NULL,
    normalized_alias varchar(255) NOT NULL, language varchar(16) NOT NULL, origin varchar(16) NOT NULL CHECK (origin IN ('source','model','user')),
    confirmed boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (entity_id, normalized_alias, language)
);
CREATE INDEX IF NOT EXISTS entity_aliases_trgm_idx ON entity_aliases USING gin (normalized_alias gin_trgm_ops);

CREATE TABLE IF NOT EXISTS event_entities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    event_id bigint NOT NULL REFERENCES events(id) ON DELETE CASCADE, entity_id bigint NOT NULL REFERENCES entities(id) ON DELETE RESTRICT,
    role varchar(64) NOT NULL, confidence numeric(5,2) NOT NULL CHECK (confidence BETWEEN 0 AND 100),
    origin varchar(16) NOT NULL CHECK (origin IN ('source','model','user')), confirmed boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (event_id, entity_id, role)
);

CREATE TABLE IF NOT EXISTS event_claims (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    event_id bigint NOT NULL REFERENCES events(id) ON DELETE RESTRICT, normalized_claim text NOT NULL, claim_hash char(64) NOT NULL,
    status varchar(24) NOT NULL CHECK (status IN ('unverified','single_source','corroborated','disputed','retracted')),
    confidence numeric(5,2) NOT NULL DEFAULT 0 CHECK (confidence BETWEEN 0 AND 100), first_seen_at timestamptz NOT NULL, last_seen_at timestamptz NOT NULL,
    manual_locked boolean NOT NULL DEFAULT false, created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    updated_by bigint REFERENCES users(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (event_id, claim_hash)
);
CREATE INDEX IF NOT EXISTS event_claims_status_idx ON event_claims(event_id, status);

CREATE TABLE IF NOT EXISTS claim_evidences (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    claim_id bigint NOT NULL REFERENCES event_claims(id) ON DELETE CASCADE, content_id bigint NOT NULL REFERENCES contents(id) ON DELETE RESTRICT,
    stance varchar(16) NOT NULL CHECK (stance IN ('supports','contradicts','mentions')), evidence_locator text NOT NULL,
    short_excerpt varchar(500) NOT NULL DEFAULT '', confidence numeric(5,2) NOT NULL CHECK (confidence BETWEEN 0 AND 100),
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (claim_id, content_id, stance)
);

CREATE TABLE IF NOT EXISTS topics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    topic_key varchar(128) NOT NULL UNIQUE, title varchar(255) NOT NULL, summary text NOT NULL DEFAULT '',
    status varchar(16) NOT NULL DEFAULT 'active' CHECK (status IN ('active','archived','merged')),
    parent_topic_id bigint REFERENCES topics(id) ON DELETE SET NULL, merged_into_id bigint REFERENCES topics(id) ON DELETE SET NULL,
    owner_id bigint REFERENCES users(id) ON DELETE SET NULL, manual_locked boolean NOT NULL DEFAULT false,
    created_by bigint REFERENCES users(id) ON DELETE SET NULL, updated_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS topic_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    topic_id bigint NOT NULL REFERENCES topics(id) ON DELETE CASCADE, event_id bigint NOT NULL REFERENCES events(id) ON DELETE RESTRICT,
    relation_type varchar(16) NOT NULL CHECK (relation_type IN ('evidence_for','milestone','update','contradiction')),
    relevance_score numeric(5,2) NOT NULL CHECK (relevance_score BETWEEN 0 AND 100),
    origin varchar(16) NOT NULL CHECK (origin IN ('rule','model','user')), confirmed boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (topic_id, event_id, relation_type)
);

CREATE TABLE IF NOT EXISTS topic_entities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    topic_id bigint NOT NULL REFERENCES topics(id) ON DELETE CASCADE, entity_id bigint NOT NULL REFERENCES entities(id) ON DELETE RESTRICT,
    relation_type varchar(64) NOT NULL, confidence numeric(5,2) NOT NULL CHECK (confidence BETWEEN 0 AND 100),
    origin varchar(16) NOT NULL CHECK (origin IN ('rule','model','user')), confirmed boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (topic_id, entity_id, relation_type)
);

CREATE TABLE IF NOT EXISTS topic_relations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    from_topic_id bigint NOT NULL REFERENCES topics(id) ON DELETE CASCADE, to_topic_id bigint NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    relation_type varchar(16) NOT NULL CHECK (relation_type IN ('parent_of','related_to','evolves_from','opposes')),
    confidence numeric(5,2) NOT NULL CHECK (confidence BETWEEN 0 AND 100), confirmed boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (from_topic_id <> to_topic_id), UNIQUE (from_topic_id, to_topic_id, relation_type)
);

CREATE TABLE IF NOT EXISTS entity_relations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    from_entity_id bigint NOT NULL REFERENCES entities(id) ON DELETE CASCADE, to_entity_id bigint NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
    relation_type varchar(64) NOT NULL, confidence numeric(5,2) NOT NULL CHECK (confidence BETWEEN 0 AND 100),
    valid_from timestamptz, valid_to timestamptz, origin varchar(16) NOT NULL CHECK (origin IN ('rule','model','user')),
    confirmed boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (from_entity_id <> to_entity_id), CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from),
    UNIQUE NULLS NOT DISTINCT (from_entity_id, to_entity_id, relation_type, valid_from)
);

CREATE TABLE IF NOT EXISTS ai_model_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    name varchar(120) NOT NULL, task_type varchar(24) NOT NULL CHECK (task_type IN ('embedding','term_expansion')),
    provider varchar(120) NOT NULL CHECK (provider IN ('openai','onnx')), model_name varchar(255) NOT NULL, endpoint text CHECK (endpoint IS NULL), credential_ref text,
    parameters jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (parameters = '{}'::jsonb), timeout_seconds integer NOT NULL DEFAULT 30 CHECK (timeout_seconds > 0),
    daily_budget numeric(12,4), fallback_priority smallint NOT NULL DEFAULT 100, enabled boolean NOT NULL DEFAULT true,
    created_by bigint REFERENCES users(id) ON DELETE SET NULL, updated_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz,
    model_version varchar(64) NOT NULL,
    embedding_dimensions smallint,
    max_attempts smallint NOT NULL DEFAULT 1 CHECK (max_attempts BETWEEN 1 AND 3),
    max_cost numeric(12,4) NOT NULL CHECK (max_cost > 0),
    CHECK ((provider = 'openai' AND credential_ref = 'env:OPENAI_API_KEY') OR (provider = 'onnx' AND credential_ref IS NULL)),
    CHECK ((task_type = 'embedding' AND embedding_dimensions = 1024) OR (task_type = 'term_expansion' AND embedding_dimensions IS NULL)),
    CHECK ((provider = 'onnx' AND task_type = 'embedding') OR provider = 'openai'),
    CHECK (daily_budget IS NULL OR daily_budget > 0),
    CHECK (daily_budget IS NULL OR daily_budget >= max_cost)
);
CREATE UNIQUE INDEX IF NOT EXISTS ai_model_profiles_active_name_uq ON ai_model_profiles(name) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    report_type varchar(16) NOT NULL CHECK (report_type IN ('daily','weekly')), monitor_id bigint REFERENCES monitors(id) ON DELETE SET NULL,
    period_start timestamptz NOT NULL, period_end timestamptz NOT NULL, timezone varchar(64) NOT NULL, title text NOT NULL,
    summary text NOT NULL DEFAULT '', body text NOT NULL DEFAULT '', status varchar(16) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','failed','archived')),
    generated_at timestamptz, published_at timestamptz, version_no integer NOT NULL DEFAULT 1 CHECK (version_no > 0),
    created_by bigint REFERENCES users(id) ON DELETE SET NULL, updated_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz,
    CHECK (period_end > period_start)
);
CREATE UNIQUE INDEX IF NOT EXISTS reports_period_version_uq ON reports(report_type, COALESCE(monitor_id, 0), period_start, period_end, version_no);
CREATE INDEX IF NOT EXISTS reports_list_idx ON reports(report_type, monitor_id, period_start DESC, id DESC);

CREATE TABLE IF NOT EXISTS report_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    report_id bigint NOT NULL REFERENCES reports(id) ON DELETE CASCADE, event_id bigint NOT NULL REFERENCES events(id) ON DELETE RESTRICT,
    rank integer NOT NULL CHECK (rank > 0), section varchar(64) NOT NULL, inclusion_reason text NOT NULL DEFAULT '',
    title_snapshot text NOT NULL, summary_snapshot text NOT NULL DEFAULT '', heat_score_snapshot numeric(7,2) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (report_id, event_id), UNIQUE (report_id, rank)
);

CREATE TABLE IF NOT EXISTS report_subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT, monitor_id bigint REFERENCES monitors(id) ON DELETE SET NULL,
    report_type varchar(16) NOT NULL CHECK (report_type IN ('daily','weekly')), channel varchar(16) NOT NULL CHECK (channel IN ('email','rss')),
    recipient varchar(254), rss_token_hash char(64), timezone varchar(64) NOT NULL, schedule varchar(64) NOT NULL,
    enabled boolean NOT NULL DEFAULT true, created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    updated_by bigint REFERENCES users(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz,
    CHECK ((channel = 'email' AND recipient IS NOT NULL AND rss_token_hash IS NULL) OR (channel = 'rss' AND rss_token_hash IS NOT NULL AND recipient IS NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS report_subscriptions_active_scope_uq ON report_subscriptions(user_id, COALESCE(monitor_id, 0), report_type, channel) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS knowledge_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    document_type varchar(16) NOT NULL CHECK (document_type IN ('event','topic','report')),
    event_id bigint REFERENCES events(id) ON DELETE RESTRICT, topic_id bigint REFERENCES topics(id) ON DELETE RESTRICT,
    report_id bigint REFERENCES reports(id) ON DELETE RESTRICT, vault_path text NOT NULL UNIQUE, revision_no bigint NOT NULL DEFAULT 0 CHECK (revision_no >= 0),
    content_hash char(64), generated_hash char(64), status varchar(16) NOT NULL DEFAULT 'planned' CHECK (status IN ('planned','active','conflict','archived','missing')),
    last_written_at timestamptz, created_by bigint REFERENCES users(id) ON DELETE SET NULL, updated_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (num_nonnulls(event_id, topic_id, report_id) = 1)
);

CREATE TABLE IF NOT EXISTS knowledge_change_proposals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    document_id bigint NOT NULL REFERENCES knowledge_documents(id) ON DELETE RESTRICT,
    change_type varchar(16) NOT NULL CHECK (change_type IN ('create','update','merge','archive')),
    base_revision_no bigint NOT NULL CHECK (base_revision_no >= 0), base_hash char(64), proposed_frontmatter jsonb NOT NULL DEFAULT '{}'::jsonb,
    proposed_body text NOT NULL DEFAULT '', diff_summary text NOT NULL DEFAULT '', reason text NOT NULL DEFAULT '',
    status varchar(16) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected','conflict','applied','failed')),
    requested_by bigint REFERENCES users(id) ON DELETE SET NULL, reviewed_by bigint REFERENCES users(id) ON DELETE SET NULL,
    reviewed_at timestamptz, applied_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS knowledge_change_proposals_status_idx ON knowledge_change_proposals(status, created_at, id);

CREATE TABLE IF NOT EXISTS knowledge_annotations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    document_id bigint NOT NULL REFERENCES knowledge_documents(id) ON DELETE RESTRICT, author_id bigint REFERENCES users(id) ON DELETE SET NULL,
    annotation_type varchar(16) NOT NULL CHECK (annotation_type IN ('note','correction','question')), body text NOT NULL,
    status varchar(16) NOT NULL DEFAULT 'active' CHECK (status IN ('active','resolved','archived')),
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS retention_policies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    data_class varchar(64) NOT NULL UNIQUE, retention_days integer NOT NULL CHECK (retention_days > 0),
    action varchar(16) NOT NULL CHECK (action IN ('archive','delete')), enabled boolean NOT NULL DEFAULT true,
    description text NOT NULL DEFAULT '', created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    updated_by bigint REFERENCES users(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS auth_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    family_id uuid NOT NULL UNIQUE, absolute_expires_at timestamptz NOT NULL, last_seen_at timestamptz NOT NULL DEFAULT now(),
    revoked_at timestamptz, revoke_reason varchar(120), created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (absolute_expires_at > created_at)
);
CREATE INDEX IF NOT EXISTS auth_sessions_active_user_idx ON auth_sessions(user_id, absolute_expires_at) WHERE revoked_at IS NULL;

CREATE OR REPLACE FUNCTION enforce_auth_session_absolute_expiry_immutable()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.absolute_expires_at IS DISTINCT FROM OLD.absolute_expires_at THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'auth_sessions_absolute_expiry_immutable',
            MESSAGE = 'auth session absolute expiry is immutable';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS auth_sessions_absolute_expiry_immutable ON auth_sessions;
CREATE TRIGGER auth_sessions_absolute_expiry_immutable
BEFORE UPDATE OF absolute_expires_at ON auth_sessions
FOR EACH ROW EXECUTE FUNCTION enforce_auth_session_absolute_expiry_immutable();

CREATE TABLE IF NOT EXISTS auth_refresh_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id bigint NOT NULL REFERENCES auth_sessions(id) ON DELETE CASCADE,
    token_hash char(64) NOT NULL UNIQUE, expires_at timestamptz NOT NULL,
    used_at timestamptz, revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (expires_at > created_at)
);
CREATE INDEX IF NOT EXISTS auth_refresh_tokens_session_expiry_idx ON auth_refresh_tokens(session_id, expires_at);

CREATE OR REPLACE FUNCTION enforce_auth_refresh_token_expiry()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    session_absolute_expires_at timestamptz;
BEGIN
    SELECT absolute_expires_at INTO session_absolute_expires_at
    FROM auth_sessions
    WHERE id = NEW.session_id;
    IF NOT FOUND THEN
        RETURN NEW;
    END IF;
    IF NEW.expires_at > session_absolute_expires_at THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'auth_refresh_tokens_expires_within_session_check',
            MESSAGE = 'auth refresh token expiry must not exceed session absolute expiry';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS auth_refresh_tokens_expires_within_session_check ON auth_refresh_tokens;
CREATE TRIGGER auth_refresh_tokens_expires_within_session_check
BEFORE INSERT OR UPDATE OF session_id, expires_at ON auth_refresh_tokens
FOR EACH ROW EXECUTE FUNCTION enforce_auth_refresh_token_expiry();

CREATE TABLE IF NOT EXISTS source_checkpoints (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 1,
    monitor_source_id bigint NOT NULL UNIQUE REFERENCES monitor_sources(id) ON DELETE CASCADE, query_hash char(64) NOT NULL,
    cursor_value text, etag text, last_modified text, high_watermark timestamptz,
    last_successful_run_id bigint, last_fetched_at timestamptz, next_poll_at timestamptz NOT NULL,
    consecutive_failures integer NOT NULL DEFAULT 0 CHECK (consecutive_failures >= 0), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS source_checkpoints_poll_idx ON source_checkpoints(next_poll_at, monitor_source_id);

CREATE TABLE IF NOT EXISTS collection_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, source_connection_id bigint NOT NULL REFERENCES source_connections(id) ON DELETE RESTRICT,
    query_signature char(64) NOT NULL, request_cursor text, next_cursor text, etag text, last_modified text,
    retry_after timestamptz, page_count integer NOT NULL DEFAULT 0 CHECK (page_count >= 0),
    window_start timestamptz NOT NULL, window_end timestamptz NOT NULL CHECK (window_end > window_start),
    trigger_type varchar(16) NOT NULL CHECK (trigger_type IN ('schedule','manual','retry','reconcile')),
    scheduled_at timestamptz NOT NULL, started_at timestamptz, finished_at timestamptz,
    status varchar(16) NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','running','succeeded','failed','cancelled')),
    candidate_count bigint NOT NULL DEFAULT 0 CHECK (candidate_count >= 0), accepted_count bigint NOT NULL DEFAULT 0 CHECK (accepted_count >= 0),
    rejected_count bigint NOT NULL DEFAULT 0 CHECK (rejected_count >= 0), error_code varchar(64),
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (source_connection_id, query_signature, window_start, window_end),
    UNIQUE (id, source_connection_id)
);

ALTER TABLE source_checkpoints DROP CONSTRAINT IF EXISTS source_checkpoints_last_successful_run_fkey;
ALTER TABLE source_checkpoints
    ADD CONSTRAINT source_checkpoints_last_successful_run_fkey
    FOREIGN KEY (last_successful_run_id) REFERENCES collection_runs(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS collection_run_targets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_run_id bigint NOT NULL REFERENCES collection_runs(id) ON DELETE CASCADE,
    monitor_source_id bigint NOT NULL, monitor_config_version_id bigint NOT NULL,
    target_status varchar(16) NOT NULL DEFAULT 'queued' CHECK (target_status IN ('queued','running','succeeded','failed','cancelled')),
    candidate_count bigint NOT NULL DEFAULT 0 CHECK (candidate_count >= 0), accepted_count bigint NOT NULL DEFAULT 0 CHECK (accepted_count >= 0),
    rejected_count bigint NOT NULL DEFAULT 0 CHECK (rejected_count >= 0), error_code varchar(64),
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (monitor_source_id, monitor_config_version_id) REFERENCES monitor_sources(id, config_version_id) ON DELETE RESTRICT,
    UNIQUE (collection_run_id, monitor_source_id),
    UNIQUE (id, collection_run_id)
);

CREATE TABLE IF NOT EXISTS collection_run_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, run_id bigint NOT NULL REFERENCES collection_runs(id) ON DELETE CASCADE,
    source_code varchar(64) NOT NULL, external_id varchar(512) NOT NULL, content_type varchar(32) NOT NULL,
    captured_item_version varchar(32) NOT NULL, captured_item jsonb NOT NULL CHECK (jsonb_typeof(captured_item) = 'object'),
    payload_hash char(64) NOT NULL, raw_payload_disposition varchar(32) NOT NULL CHECK (raw_payload_disposition IN ('discarded', 'captured_item_only')),
    content_id bigint,
    outcome varchar(16) NOT NULL CHECK (outcome IN ('captured','skipped','failed')), reason_code varchar(64), observed_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(), source_connection_id bigint NOT NULL,
    ingestion_status varchar(16) NOT NULL DEFAULT 'pending' CHECK (ingestion_status IN ('pending','succeeded','failed')),
    ingestion_error_code varchar(64),
    FOREIGN KEY (run_id, source_connection_id) REFERENCES collection_runs(id, source_connection_id) ON DELETE CASCADE,
    FOREIGN KEY (content_id, source_connection_id) REFERENCES contents(id, source_connection_id) ON DELETE SET NULL (content_id),
    CHECK (outcome = 'captured' AND (
            (content_id IS NULL AND ingestion_status = 'pending' AND ingestion_error_code IS NULL)
            OR (content_id IS NULL AND ingestion_status = 'failed' AND ingestion_error_code IS NOT NULL)
            OR (content_id IS NOT NULL AND ingestion_status = 'succeeded' AND ingestion_error_code IS NULL)
        ) OR (outcome IN ('skipped', 'failed') AND content_id IS NULL AND ingestion_status = 'pending' AND ingestion_error_code IS NULL)),
    UNIQUE (run_id, external_id), UNIQUE (id, run_id)
);

CREATE TABLE IF NOT EXISTS collection_run_target_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_run_id bigint NOT NULL,
    collection_run_target_id bigint NOT NULL,
    collection_run_item_id bigint NOT NULL,
    outcome varchar(16) NOT NULL CHECK (outcome IN ('captured','skipped','failed')), reason_code varchar(64),
    created_at timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (collection_run_target_id, collection_run_id) REFERENCES collection_run_targets(id, collection_run_id) ON DELETE CASCADE,
    FOREIGN KEY (collection_run_item_id, collection_run_id) REFERENCES collection_run_items(id, run_id) ON DELETE CASCADE,
    UNIQUE (collection_run_target_id, collection_run_item_id)
);

CREATE TABLE IF NOT EXISTS content_metric_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, content_id bigint NOT NULL REFERENCES contents(id) ON DELETE RESTRICT,
    captured_at timestamptz NOT NULL, view_count bigint CHECK (view_count >= 0), like_count bigint CHECK (like_count >= 0),
    comment_count bigint CHECK (comment_count >= 0), share_count bigint CHECK (share_count >= 0),
    extra_metrics jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (content_id, captured_at)
);

CREATE TABLE IF NOT EXISTS event_metric_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_id bigint NOT NULL REFERENCES events(id) ON DELETE RESTRICT,
    captured_at timestamptz NOT NULL, heat_score numeric(7,2) NOT NULL CHECK (heat_score >= 0), trend_score numeric(7,2) NOT NULL,
    source_count bigint NOT NULL DEFAULT 0 CHECK (source_count >= 0), content_count bigint NOT NULL DEFAULT 0 CHECK (content_count >= 0),
    created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (event_id, captured_at)
);

CREATE TABLE IF NOT EXISTS ai_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_type varchar(64) NOT NULL, target_type varchar(64) NOT NULL, target_id bigint NOT NULL,
    model_profile_id bigint NOT NULL REFERENCES ai_model_profiles(id) ON DELETE RESTRICT, prompt_version varchar(64) NOT NULL, schema_version varchar(64) NOT NULL,
    input_hash char(64) NOT NULL, request_object_key text, response_object_key text, structured_result jsonb NOT NULL DEFAULT '{}'::jsonb,
    tokens bigint NOT NULL DEFAULT 0 CHECK (tokens >= 0), cost numeric(12,4) NOT NULL DEFAULT 0 CHECK (cost >= 0), latency_ms bigint NOT NULL DEFAULT 0 CHECK (latency_ms >= 0),
    status varchar(16) NOT NULL CHECK (status IN ('queued','running','validating','retry_wait','succeeded','failed','cancelled')),
    created_at timestamptz NOT NULL DEFAULT now(), started_at timestamptz, finished_at timestamptz,
    model_profile_version bigint NOT NULL,
    model_version varchar(64) NOT NULL,
    parameters_version varchar(64) NOT NULL,
    input_schema_version varchar(64) NOT NULL,
    evidence_set_hash char(64) NOT NULL,
    reuse_key char(64) NOT NULL,
    attempt smallint NOT NULL DEFAULT 1 CHECK (attempt BETWEEN 1 AND 3),
    max_attempts smallint NOT NULL DEFAULT 1 CHECK (max_attempts BETWEEN 1 AND 3),
    repair_attempted boolean NOT NULL DEFAULT false,
    retry_after timestamptz,
    error_code integer,
    budget_day date NOT NULL,
    reserved_cost numeric(12,4) NOT NULL DEFAULT 0 CHECK (reserved_cost >= 0),
    lease_expires_at timestamptz,
    CHECK (request_object_key IS NULL AND response_object_key IS NULL),
    CHECK (attempt <= max_attempts),
    CHECK (status IN ('queued','running','validating','retry_wait') AND lease_expires_at IS NOT NULL OR status IN ('succeeded','failed','cancelled') AND lease_expires_at IS NULL)
);
CREATE UNIQUE INDEX IF NOT EXISTS ai_runs_reuse_succeeded_uq ON ai_runs(reuse_key) WHERE status = 'succeeded';
CREATE UNIQUE INDEX IF NOT EXISTS ai_runs_reuse_inflight_uq ON ai_runs(reuse_key) WHERE status IN ('queued','running','validating','retry_wait');

CREATE TABLE IF NOT EXISTS ai_budget_ledgers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_profile_id bigint NOT NULL REFERENCES ai_model_profiles(id) ON DELETE RESTRICT,
    budget_day date NOT NULL,
    reserved_cost numeric(12,4) NOT NULL DEFAULT 0 CHECK (reserved_cost >= 0),
    settled_cost numeric(12,4) NOT NULL DEFAULT 0 CHECK (settled_cost >= 0),
    overage_blocked boolean NOT NULL DEFAULT false,
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (model_profile_id, budget_day)
);

CREATE TABLE IF NOT EXISTS ai_run_evidences (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ai_run_id bigint NOT NULL REFERENCES ai_runs(id) ON DELETE CASCADE,
    content_id bigint NOT NULL REFERENCES contents(id) ON DELETE RESTRICT, evidence_role varchar(32) NOT NULL, position integer NOT NULL DEFAULT 0 CHECK (position >= 0),
    created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (ai_run_id, content_id, evidence_role)
);

CREATE TABLE IF NOT EXISTS content_embeddings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, content_id bigint NOT NULL REFERENCES contents(id) ON DELETE CASCADE,
    model_profile_id bigint NOT NULL REFERENCES ai_model_profiles(id) ON DELETE RESTRICT, model_version varchar(64) NOT NULL, input_hash char(64) NOT NULL,
    embedding halfvec(1024) NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), model_profile_version bigint NOT NULL,
    ai_run_id bigint NOT NULL REFERENCES ai_runs(id) ON DELETE RESTRICT,
    UNIQUE (content_id, model_profile_id, model_version, input_hash)
);
CREATE INDEX IF NOT EXISTS content_embeddings_active_hnsw_idx ON content_embeddings USING hnsw (embedding halfvec_cosine_ops) WHERE active;
CREATE UNIQUE INDEX IF NOT EXISTS content_embeddings_one_active_per_profile_uq ON content_embeddings(content_id, model_profile_id) WHERE active;

CREATE TABLE IF NOT EXISTS monitor_embeddings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, monitor_id bigint NOT NULL REFERENCES monitors(id) ON DELETE CASCADE,
    model_profile_id bigint NOT NULL REFERENCES ai_model_profiles(id) ON DELETE RESTRICT, model_version varchar(64) NOT NULL, input_hash char(64) NOT NULL,
    query_text text NOT NULL, embedding halfvec(1024) NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), model_profile_version bigint NOT NULL,
    ai_run_id bigint NOT NULL REFERENCES ai_runs(id) ON DELETE RESTRICT,
    UNIQUE (monitor_id, model_profile_id, model_version, input_hash)
);
CREATE INDEX IF NOT EXISTS monitor_embeddings_active_hnsw_idx ON monitor_embeddings USING hnsw (embedding halfvec_cosine_ops) WHERE active;
CREATE UNIQUE INDEX IF NOT EXISTS monitor_embeddings_one_active_per_profile_uq ON monitor_embeddings(monitor_id, model_profile_id) WHERE active;

CREATE TABLE IF NOT EXISTS event_embeddings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_id bigint NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    model_profile_id bigint NOT NULL REFERENCES ai_model_profiles(id) ON DELETE RESTRICT, model_version varchar(64) NOT NULL, input_hash char(64) NOT NULL,
    embedding halfvec(1024) NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), model_profile_version bigint NOT NULL,
    ai_run_id bigint NOT NULL REFERENCES ai_runs(id) ON DELETE RESTRICT,
    UNIQUE (event_id, model_profile_id, model_version, input_hash)
);
CREATE INDEX IF NOT EXISTS event_embeddings_active_hnsw_idx ON event_embeddings USING hnsw (embedding halfvec_cosine_ops) WHERE active;
CREATE UNIQUE INDEX IF NOT EXISTS event_embeddings_one_active_per_profile_uq ON event_embeddings(event_id, model_profile_id) WHERE active;

CREATE TABLE IF NOT EXISTS topic_embeddings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, topic_id bigint NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    model_profile_id bigint NOT NULL REFERENCES ai_model_profiles(id) ON DELETE RESTRICT, model_version varchar(64) NOT NULL, input_hash char(64) NOT NULL,
    embedding halfvec(1024) NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), model_profile_version bigint NOT NULL,
    ai_run_id bigint NOT NULL REFERENCES ai_runs(id) ON DELETE RESTRICT,
    UNIQUE (topic_id, model_profile_id, model_version, input_hash)
);
CREATE INDEX IF NOT EXISTS topic_embeddings_active_hnsw_idx ON topic_embeddings USING hnsw (embedding halfvec_cosine_ops) WHERE active;
CREATE UNIQUE INDEX IF NOT EXISTS topic_embeddings_one_active_per_profile_uq ON topic_embeddings(topic_id, model_profile_id) WHERE active;

CREATE TABLE IF NOT EXISTS knowledge_revisions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, document_id bigint NOT NULL REFERENCES knowledge_documents(id) ON DELETE RESTRICT,
    revision_no bigint NOT NULL CHECK (revision_no >= 0), source varchar(16) NOT NULL CHECK (source IN ('user','proposal','reconcile')),
    proposal_id bigint REFERENCES knowledge_change_proposals(id) ON DELETE SET NULL, previous_hash char(64), new_hash char(64),
    snapshot_object_key text, frontmatter_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb, created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (document_id, revision_no)
);

CREATE TABLE IF NOT EXISTS vault_sync_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, run_type varchar(16) NOT NULL CHECK (run_type IN ('full','incremental','reconcile')),
    started_at timestamptz, finished_at timestamptz, status varchar(16) NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','running','succeeded','failed','cancelled')),
    scanned_count bigint NOT NULL DEFAULT 0 CHECK (scanned_count >= 0), changed_count bigint NOT NULL DEFAULT 0 CHECK (changed_count >= 0),
    conflict_count bigint NOT NULL DEFAULT 0 CHECK (conflict_count >= 0), error text, created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS report_deliveries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, report_id bigint NOT NULL REFERENCES reports(id) ON DELETE RESTRICT,
    subscription_id bigint NOT NULL REFERENCES report_subscriptions(id) ON DELETE RESTRICT, idempotency_key varchar(128) NOT NULL UNIQUE,
    status varchar(16) NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','claimed','succeeded','retrying','failed','cancelled')),
    next_attempt_at timestamptz, succeeded_at timestamptz, last_error text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (report_id, subscription_id)
);
CREATE INDEX IF NOT EXISTS report_deliveries_next_attempt_idx ON report_deliveries(status, next_attempt_at, id);

CREATE TABLE IF NOT EXISTS delivery_attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, delivery_id bigint NOT NULL REFERENCES report_deliveries(id) ON DELETE CASCADE,
    attempt_no integer NOT NULL CHECK (attempt_no > 0), started_at timestamptz NOT NULL, finished_at timestamptz,
    status varchar(16) NOT NULL CHECK (status IN ('started','succeeded','failed')), provider_message_id varchar(255), response_code integer, error text,
    created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (delivery_id, attempt_no)
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, actor_type varchar(32) NOT NULL, actor_id bigint,
    action varchar(120) NOT NULL, resource_type varchar(64) NOT NULL, resource_id bigint, request_id varchar(128), trace_id varchar(128),
    before_data jsonb, after_data jsonb, result varchar(16) NOT NULL CHECK (result IN ('success','failure','denied')),
    ip_hash char(64), created_at timestamptz NOT NULL DEFAULT now()
);

-- River job metadata belongs to the job-queue infrastructure and is not exposed
-- through application repositories or public APIs. The runtime integration in
-- PLAN-002 validates its expected River version before workers are enabled.
CREATE TABLE IF NOT EXISTS river_job (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, kind text NOT NULL, args jsonb NOT NULL DEFAULT '{}'::jsonb,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb, state text NOT NULL DEFAULT 'available', attempt integer NOT NULL DEFAULT 0,
    max_attempts integer NOT NULL DEFAULT 25, priority smallint NOT NULL DEFAULT 1, scheduled_at timestamptz NOT NULL DEFAULT now(),
    attempted_at timestamptz, finalized_at timestamptz, unique_key bytea, tags varchar(255)[] NOT NULL DEFAULT '{}',
    errors jsonb[] NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE NULLS NOT DISTINCT (kind, unique_key)
);
CREATE INDEX IF NOT EXISTS river_job_fetch_idx ON river_job(state, scheduled_at, priority, id);

CREATE TABLE IF NOT EXISTS river_job_attempt (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, job_id bigint NOT NULL REFERENCES river_job(id) ON DELETE CASCADE,
    attempt integer NOT NULL, error text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (job_id, attempt)
);

CREATE TABLE IF NOT EXISTS river_queue (
    name text PRIMARY KEY, paused_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS river_leader (
    name text PRIMARY KEY, elected_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS river_migration (
    version bigint PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now()
);
