// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keyword_monitors.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO keyword_monitors (user_id, name, query_text, language, region, poll_interval_minutes, alert_enabled, alert_threshold_config)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, name, query_text, language, region, status, poll_interval_minutes, alert_enabled, alert_threshold_config, last_polled_at, created_at, updated_at
`

type CreateMonitorParams struct {
	UserID               int64  `json:"user_id"`
	Name                 string `json:"name"`
	QueryText            string `json:"query_text"`
	Language             string `json:"language"`
	Region               string `json:"region"`
	PollIntervalMinutes  int32  `json:"poll_interval_minutes"`
	AlertEnabled         bool   `json:"alert_enabled"`
	AlertThresholdConfig []byte `json:"alert_threshold_config"`
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (KeywordMonitor, error) {
	row := q.db.QueryRow(ctx, createMonitor,
		arg.UserID,
		arg.Name,
		arg.QueryText,
		arg.Language,
		arg.Region,
		arg.PollIntervalMinutes,
		arg.AlertEnabled,
		arg.AlertThresholdConfig,
	)
	var i KeywordMonitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.QueryText,
		&i.Language,
		&i.Region,
		&i.Status,
		&i.PollIntervalMinutes,
		&i.AlertEnabled,
		&i.AlertThresholdConfig,
		&i.LastPolledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMonitorByID = `-- name: GetMonitorByID :one
SELECT id, user_id, name, query_text, language, region, status, poll_interval_minutes, alert_enabled, alert_threshold_config, last_polled_at, created_at, updated_at
FROM keyword_monitors
WHERE id = $1
`

func (q *Queries) GetMonitorByID(ctx context.Context, id int64) (KeywordMonitor, error) {
	row := q.db.QueryRow(ctx, getMonitorByID, id)
	var i KeywordMonitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.QueryText,
		&i.Language,
		&i.Region,
		&i.Status,
		&i.PollIntervalMinutes,
		&i.AlertEnabled,
		&i.AlertThresholdConfig,
		&i.LastPolledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMonitorsByUser = `-- name: ListMonitorsByUser :many
SELECT id, user_id, name, query_text, language, region, status, poll_interval_minutes, alert_enabled, alert_threshold_config, last_polled_at, created_at, updated_at
FROM keyword_monitors
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListMonitorsByUser(ctx context.Context, userID int64) ([]KeywordMonitor, error) {
	rows, err := q.db.Query(ctx, listMonitorsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KeywordMonitor{}
	for rows.Next() {
		var i KeywordMonitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.QueryText,
			&i.Language,
			&i.Region,
			&i.Status,
			&i.PollIntervalMinutes,
			&i.AlertEnabled,
			&i.AlertThresholdConfig,
			&i.LastPolledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMonitor = `-- name: UpdateMonitor :one
UPDATE keyword_monitors
SET name = coalesce($1, name),
    query_text = coalesce($2, query_text),
    language = coalesce($3, language),
    region = coalesce($4, region),
    poll_interval_minutes = coalesce($5, poll_interval_minutes),
    alert_enabled = coalesce($6, alert_enabled),
    status = coalesce($7, status),
    updated_at = now()
WHERE id = $8
RETURNING id, user_id, name, query_text, language, region, status, poll_interval_minutes, alert_enabled, alert_threshold_config, last_polled_at, created_at, updated_at
`

type UpdateMonitorParams struct {
	Name                pgtype.Text `json:"name"`
	QueryText           pgtype.Text `json:"query_text"`
	Language            pgtype.Text `json:"language"`
	Region              pgtype.Text `json:"region"`
	PollIntervalMinutes pgtype.Int4 `json:"poll_interval_minutes"`
	AlertEnabled        pgtype.Bool `json:"alert_enabled"`
	Status              pgtype.Text `json:"status"`
	ID                  int64       `json:"id"`
}

func (q *Queries) UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (KeywordMonitor, error) {
	row := q.db.QueryRow(ctx, updateMonitor,
		arg.Name,
		arg.QueryText,
		arg.Language,
		arg.Region,
		arg.PollIntervalMinutes,
		arg.AlertEnabled,
		arg.Status,
		arg.ID,
	)
	var i KeywordMonitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.QueryText,
		&i.Language,
		&i.Region,
		&i.Status,
		&i.PollIntervalMinutes,
		&i.AlertEnabled,
		&i.AlertThresholdConfig,
		&i.LastPolledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
