// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID            int64              `json:"id"`
	MonitorID     int64              `json:"monitor_id"`
	TopicID       pgtype.Int8        `json:"topic_id"`
	AlertType     string             `json:"alert_type"`
	Title         string             `json:"title"`
	Message       string             `json:"message"`
	Severity      string             `json:"severity"`
	TriggerScore  pgtype.Numeric     `json:"trigger_score"`
	TriggerReason string             `json:"trigger_reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type EmailDelivery struct {
	ID                int64              `json:"id"`
	NotificationID    int64              `json:"notification_id"`
	RecipientEmail    string             `json:"recipient_email"`
	Provider          string             `json:"provider"`
	ProviderMessageID string             `json:"provider_message_id"`
	Status            string             `json:"status"`
	ErrorMessage      string             `json:"error_message"`
	SentAt            pgtype.Timestamptz `json:"sent_at"`
}

type KeywordMonitor struct {
	ID                   int64              `json:"id"`
	UserID               int64              `json:"user_id"`
	Name                 string             `json:"name"`
	QueryText            string             `json:"query_text"`
	Language             string             `json:"language"`
	Region               string             `json:"region"`
	Status               string             `json:"status"`
	PollIntervalMinutes  int32              `json:"poll_interval_minutes"`
	AlertEnabled         bool               `json:"alert_enabled"`
	AlertThresholdConfig []byte             `json:"alert_threshold_config"`
	LastPolledAt         pgtype.Timestamptz `json:"last_polled_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type MonitorPostHit struct {
	ID                   int64              `json:"id"`
	MonitorID            int64              `json:"monitor_id"`
	PostID               int64              `json:"post_id"`
	MatchedKeywords      []byte             `json:"matched_keywords"`
	RelevanceScore       pgtype.Numeric     `json:"relevance_score"`
	HeatScore            pgtype.Numeric     `json:"heat_score"`
	FreshnessScore       pgtype.Numeric     `json:"freshness_score"`
	AuthorInfluenceScore pgtype.Numeric     `json:"author_influence_score"`
	FinalScore           pgtype.Numeric     `json:"final_score"`
	FirstSeenAt          pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt           pgtype.Timestamptz `json:"last_seen_at"`
}

type MonitorRun struct {
	ID             int64              `json:"id"`
	MonitorID      int64              `json:"monitor_id"`
	Platform       string             `json:"platform"`
	RunType        string             `json:"run_type"`
	Status         string             `json:"status"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	FetchedCount   int32              `json:"fetched_count"`
	StoredCount    int32              `json:"stored_count"`
	ErrorMessage   string             `json:"error_message"`
	CursorSnapshot []byte             `json:"cursor_snapshot"`
}

type MonitorSnapshot struct {
	ID               int64              `json:"id"`
	MonitorID        int64              `json:"monitor_id"`
	SnapshotTime     pgtype.Timestamptz `json:"snapshot_time"`
	NewPostCount     int32              `json:"new_post_count"`
	ActiveTopicCount int32              `json:"active_topic_count"`
	TotalEngagement  int32              `json:"total_engagement"`
	TopTopicID       pgtype.Int8        `json:"top_topic_id"`
}

type PlatformAuthor struct {
	ID               int64              `json:"id"`
	Platform         string             `json:"platform"`
	PlatformAuthorID string             `json:"platform_author_id"`
	Handle           string             `json:"handle"`
	DisplayName      string             `json:"display_name"`
	FollowersCount   int32              `json:"followers_count"`
	Verified         bool               `json:"verified"`
	RawPayload       []byte             `json:"raw_payload"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type PlatformPost struct {
	ID               int64              `json:"id"`
	Platform         string             `json:"platform"`
	PlatformPostID   string             `json:"platform_post_id"`
	AuthorPlatformID string             `json:"author_platform_id"`
	AuthorName       string             `json:"author_name"`
	AuthorHandle     string             `json:"author_handle"`
	ContentText      string             `json:"content_text"`
	ContentLang      string             `json:"content_lang"`
	PostUrl          string             `json:"post_url"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	LikeCount        int32              `json:"like_count"`
	ReplyCount       int32              `json:"reply_count"`
	RepostCount      int32              `json:"repost_count"`
	QuoteCount       int32              `json:"quote_count"`
	ViewCount        int32              `json:"view_count"`
	RawPayload       []byte             `json:"raw_payload"`
	NormalizedHash   string             `json:"normalized_hash"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Topic struct {
	ID                   int64              `json:"id"`
	MonitorID            int64              `json:"monitor_id"`
	TopicKey             string             `json:"topic_key"`
	Title                string             `json:"title"`
	Summary              string             `json:"summary"`
	Status               string             `json:"status"`
	FirstDetectedAt      pgtype.Timestamptz `json:"first_detected_at"`
	LastActiveAt         pgtype.Timestamptz `json:"last_active_at"`
	CurrentHeatScore     pgtype.Numeric     `json:"current_heat_score"`
	TrendDirection       string             `json:"trend_direction"`
	RepresentativePostID pgtype.Int8        `json:"representative_post_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type TopicPost struct {
	ID               int64              `json:"id"`
	TopicID          int64              `json:"topic_id"`
	PostID           int64              `json:"post_id"`
	MembershipScore  pgtype.Numeric     `json:"membership_score"`
	IsRepresentative bool               `json:"is_representative"`
	AddedAt          pgtype.Timestamptz `json:"added_at"`
}

type TopicSnapshot struct {
	ID                int64              `json:"id"`
	TopicID           int64              `json:"topic_id"`
	SnapshotTime      pgtype.Timestamptz `json:"snapshot_time"`
	PostCount         int32              `json:"post_count"`
	UniqueAuthorCount int32              `json:"unique_author_count"`
	EngagementSum     int32              `json:"engagement_sum"`
	HeatScore         pgtype.Numeric     `json:"heat_score"`
	TrendVelocity     pgtype.Numeric     `json:"trend_velocity"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  string             `json:"display_name"`
	Status       string             `json:"status"`
	PlanType     string             `json:"plan_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserNotification struct {
	ID             int64              `json:"id"`
	UserID         int64              `json:"user_id"`
	AlertID        int64              `json:"alert_id"`
	Channel        string             `json:"channel"`
	DeliveryStatus string             `json:"delivery_status"`
	ReadAt         pgtype.Timestamptz `json:"read_at"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
