// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMonitor = `-- name: CreateMonitor :one

INSERT INTO keyword_monitors (user_id, name, query_text, language, region, poll_interval_minutes, alert_enabled, alert_threshold_config)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, name, query_text, language, region, status, poll_interval_minutes, alert_enabled, alert_threshold_config, last_polled_at, created_at, updated_at
`

type CreateMonitorParams struct {
	UserID               int64  `json:"user_id"`
	Name                 string `json:"name"`
	QueryText            string `json:"query_text"`
	Language             string `json:"language"`
	Region               string `json:"region"`
	PollIntervalMinutes  int32  `json:"poll_interval_minutes"`
	AlertEnabled         bool   `json:"alert_enabled"`
	AlertThresholdConfig []byte `json:"alert_threshold_config"`
}

// keyword_monitors ----------------------------------------------------------
func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (KeywordMonitor, error) {
	row := q.db.QueryRow(ctx, createMonitor,
		arg.UserID,
		arg.Name,
		arg.QueryText,
		arg.Language,
		arg.Region,
		arg.PollIntervalMinutes,
		arg.AlertEnabled,
		arg.AlertThresholdConfig,
	)
	var i KeywordMonitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.QueryText,
		&i.Language,
		&i.Region,
		&i.Status,
		&i.PollIntervalMinutes,
		&i.AlertEnabled,
		&i.AlertThresholdConfig,
		&i.LastPolledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNotification = `-- name: CreateNotification :one

INSERT INTO user_notifications (user_id, alert_id, channel, delivery_status)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, alert_id, channel, delivery_status, read_at, sent_at, created_at
`

type CreateNotificationParams struct {
	UserID         int64  `json:"user_id"`
	AlertID        int64  `json:"alert_id"`
	Channel        string `json:"channel"`
	DeliveryStatus string `json:"delivery_status"`
}

// user_notifications --------------------------------------------------------
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (UserNotification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.AlertID,
		arg.Channel,
		arg.DeliveryStatus,
	)
	var i UserNotification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlertID,
		&i.Channel,
		&i.DeliveryStatus,
		&i.ReadAt,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, display_name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, display_name, status, plan_type, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	DisplayName  string `json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Status,
		&i.PlanType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existsByEmail = `-- name: ExistsByEmail :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, existsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getMonitorByID = `-- name: GetMonitorByID :one
SELECT id, user_id, name, query_text, language, region, status, poll_interval_minutes, alert_enabled, alert_threshold_config, last_polled_at, created_at, updated_at
FROM keyword_monitors
WHERE id = $1
`

func (q *Queries) GetMonitorByID(ctx context.Context, id int64) (KeywordMonitor, error) {
	row := q.db.QueryRow(ctx, getMonitorByID, id)
	var i KeywordMonitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.QueryText,
		&i.Language,
		&i.Region,
		&i.Status,
		&i.PollIntervalMinutes,
		&i.AlertEnabled,
		&i.AlertThresholdConfig,
		&i.LastPolledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one


SELECT id, email, password_hash, display_name, status, plan_type, created_at, updated_at
FROM users
WHERE email = $1
`

// sqlc query definitions (auth, monitor, notify)
// users ---------------------------------------------------------------------
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Status,
		&i.PlanType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, display_name, status, plan_type, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Status,
		&i.PlanType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMonitorsByUser = `-- name: ListMonitorsByUser :many
SELECT id, user_id, name, query_text, language, region, status, poll_interval_minutes, alert_enabled, alert_threshold_config, last_polled_at, created_at, updated_at
FROM keyword_monitors
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListMonitorsByUser(ctx context.Context, userID int64) ([]KeywordMonitor, error) {
	rows, err := q.db.Query(ctx, listMonitorsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KeywordMonitor{}
	for rows.Next() {
		var i KeywordMonitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.QueryText,
			&i.Language,
			&i.Region,
			&i.Status,
			&i.PollIntervalMinutes,
			&i.AlertEnabled,
			&i.AlertThresholdConfig,
			&i.LastPolledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadNotifications = `-- name: ListUnreadNotifications :many
SELECT id, user_id, alert_id, channel, delivery_status, read_at, sent_at, created_at
FROM user_notifications
WHERE user_id = $1 AND read_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListUnreadNotifications(ctx context.Context, userID int64) ([]UserNotification, error) {
	rows, err := q.db.Query(ctx, listUnreadNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserNotification{}
	for rows.Next() {
		var i UserNotification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AlertID,
			&i.Channel,
			&i.DeliveryStatus,
			&i.ReadAt,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE user_notifications
SET read_at = now()
WHERE id = $1 AND user_id = $2 AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}

const updateMonitor = `-- name: UpdateMonitor :one
UPDATE keyword_monitors
SET name = coalesce($1, name),
    query_text = coalesce($2, query_text),
    language = coalesce($3, language),
    region = coalesce($4, region),
    poll_interval_minutes = coalesce($5, poll_interval_minutes),
    alert_enabled = coalesce($6, alert_enabled),
    status = coalesce($7, status),
    updated_at = now()
WHERE id = $8
RETURNING id, user_id, name, query_text, language, region, status, poll_interval_minutes, alert_enabled, alert_threshold_config, last_polled_at, created_at, updated_at
`

type UpdateMonitorParams struct {
	Name                pgtype.Text `json:"name"`
	QueryText           pgtype.Text `json:"query_text"`
	Language            pgtype.Text `json:"language"`
	Region              pgtype.Text `json:"region"`
	PollIntervalMinutes pgtype.Int4 `json:"poll_interval_minutes"`
	AlertEnabled        pgtype.Bool `json:"alert_enabled"`
	Status              pgtype.Text `json:"status"`
	ID                  int64       `json:"id"`
}

func (q *Queries) UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (KeywordMonitor, error) {
	row := q.db.QueryRow(ctx, updateMonitor,
		arg.Name,
		arg.QueryText,
		arg.Language,
		arg.Region,
		arg.PollIntervalMinutes,
		arg.AlertEnabled,
		arg.Status,
		arg.ID,
	)
	var i KeywordMonitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.QueryText,
		&i.Language,
		&i.Region,
		&i.Status,
		&i.PollIntervalMinutes,
		&i.AlertEnabled,
		&i.AlertThresholdConfig,
		&i.LastPolledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
