// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_notifications.sql

package sqlc

import (
	"context"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO user_notifications (user_id, alert_id, channel, delivery_status)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, alert_id, channel, delivery_status, read_at, sent_at, created_at
`

type CreateNotificationParams struct {
	UserID         int64  `json:"user_id"`
	AlertID        int64  `json:"alert_id"`
	Channel        string `json:"channel"`
	DeliveryStatus string `json:"delivery_status"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (UserNotification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.AlertID,
		arg.Channel,
		arg.DeliveryStatus,
	)
	var i UserNotification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlertID,
		&i.Channel,
		&i.DeliveryStatus,
		&i.ReadAt,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUnreadNotifications = `-- name: ListUnreadNotifications :many
SELECT id, user_id, alert_id, channel, delivery_status, read_at, sent_at, created_at
FROM user_notifications
WHERE user_id = $1 AND read_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListUnreadNotifications(ctx context.Context, userID int64) ([]UserNotification, error) {
	rows, err := q.db.Query(ctx, listUnreadNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserNotification{}
	for rows.Next() {
		var i UserNotification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AlertID,
			&i.Channel,
			&i.DeliveryStatus,
			&i.ReadAt,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE user_notifications
SET read_at = now()
WHERE id = $1 AND user_id = $2 AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}
