// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login with email and password",
                "operationId": "login",
                "parameters": [
                    {
                        "description": "Login payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_model_dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout and revoke session",
                "operationId": "logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/me": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get current user profile",
                "operationId": "me",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller.AuthenticatedUserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/password/reset": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Reset password with verification ticket",
                "operationId": "reset-password",
                "parameters": [
                    {
                        "description": "Password reset payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_model_dto.PasswordResetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "operationId": "register",
                "parameters": [
                    {
                        "description": "Verified registration payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_model_dto.EmailRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_controller.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/token/refresh": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh access token",
                "operationId": "refresh-token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller.AuthTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/verifications": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Send a verification code",
                "operationId": "send-verification",
                "parameters": [
                    {
                        "description": "Verification send payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_model_dto.VerificationSendRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller.VerificationSendResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/verifications/confirm": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Confirm a verification code",
                "operationId": "confirm-verification",
                "parameters": [
                    {
                        "description": "Verification confirm payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_model_dto.VerificationConfirmRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller.VerificationTicketResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/hot-events": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hot-events"
                ],
                "summary": "List hot events with filter and pagination",
                "operationId": "list-hot-events",
                "parameters": [
                    {
                        "type": "string",
                        "default": "active",
                        "description": "Status filter",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Platform filter",
                        "name": "platform",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "heat_score",
                        "description": "Sort field",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Max results",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller.HotEventListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/hot-events/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hot-events"
                ],
                "summary": "Get a hot event by ID with platform details",
                "operationId": "get-hot-event",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Hot Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller.HotEventResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/hot-events/{id}/posts": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hot-events"
                ],
                "summary": "Get posts for a hot event",
                "operationId": "get-hot-event-posts",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Hot Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller.HotEventPostsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/monitors": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "monitors"
                ],
                "summary": "List monitors",
                "operationId": "list-monitors",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller.MonitorListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "monitors"
                ],
                "summary": "Create monitor",
                "operationId": "create-monitor",
                "parameters": [
                    {
                        "description": "Monitor payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_model_dto.CreateMonitorRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_controller.MonitorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/monitors/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "monitors"
                ],
                "summary": "Get monitor",
                "operationId": "get-monitor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Monitor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller.MonitorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "monitors"
                ],
                "summary": "Update monitor",
                "operationId": "update-monitor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Monitor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Monitor update payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_model_dto.UpdateMonitorRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller.MonitorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/monitors/{id}/posts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "content"
                ],
                "summary": "List posts for a monitor",
                "operationId": "list-posts",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Monitor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller.PostListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/monitors/{id}/topics": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "topics"
                ],
                "summary": "List topics for a monitor",
                "operationId": "list-topics",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Monitor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller.TopicListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/monitors/{id}/trends": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trends"
                ],
                "summary": "Get monitor trends",
                "operationId": "get-monitor-trends",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Monitor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RFC3339 start time",
                        "name": "since",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller.TrendListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/notifications": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "List unread notifications",
                "operationId": "list-notifications",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller.NotificationListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/notifications/{id}/read": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Mark notification as read",
                "operationId": "mark-notification-read",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Notification ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller.MarkNotificationReadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/reports": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "List reports",
                "operationId": "list-reports",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Max results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by report type (daily|weekly)",
                        "name": "report_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller.ReportListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Create a report",
                "operationId": "create-report",
                "parameters": [
                    {
                        "description": "Report creation payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_model_dto.CreateReportRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_controller.ReportResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/reports/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get a report by ID",
                "operationId": "get-report",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Report ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller.ReportResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/reports/{id}/html": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get report as HTML",
                "operationId": "get-report-html",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Report ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "HTML content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/reports/{id}/send": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Mark and send a report",
                "operationId": "send-report",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Report ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller.ReportResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/topics/{id}/trends": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trends"
                ],
                "summary": "Get topic trends",
                "operationId": "get-topic-trends",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Topic ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RFC3339 start time",
                        "name": "since",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller.TrendListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/trending": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trending"
                ],
                "summary": "List trending hot events across platforms",
                "operationId": "list-trending",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Platform filter",
                        "name": "platform",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Max results",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller.TrendingListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "operationId": "health-check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_StephenQiu30_hotkey-server_internal_content.PostSummary": {
            "type": "object",
            "properties": {
                "author_handle": {
                    "type": "string"
                },
                "author_name": {
                    "type": "string"
                },
                "content_lang": {
                    "type": "string"
                },
                "content_text": {
                    "type": "string"
                },
                "final_score": {
                    "type": "number"
                },
                "freshness_score": {
                    "type": "number"
                },
                "heat_score": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "like_count": {
                    "type": "integer"
                },
                "matched_keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "platform_post_id": {
                    "type": "string"
                },
                "published_at": {
                    "type": "string"
                },
                "quote_count": {
                    "type": "integer"
                },
                "relevance_score": {
                    "type": "number"
                },
                "reply_count": {
                    "type": "integer"
                },
                "repost_count": {
                    "type": "integer"
                },
                "view_count": {
                    "type": "integer"
                }
            }
        },
        "github_com_StephenQiu30_hotkey-server_internal_model_dto.CreateMonitorRequest": {
            "type": "object",
            "properties": {
                "alert_enabled": {
                    "type": "boolean",
                    "example": true
                },
                "language": {
                    "type": "string",
                    "example": "en"
                },
                "name": {
                    "type": "string",
                    "example": "AI monitor"
                },
                "poll_interval_minutes": {
                    "type": "integer",
                    "example": 15
                },
                "query_text": {
                    "type": "string",
                    "example": "openai OR gpt"
                },
                "region": {
                    "type": "string",
                    "example": "US"
                }
            }
        },
        "github_com_StephenQiu30_hotkey-server_internal_model_dto.CreateReportRequest": {
            "type": "object",
            "properties": {
                "period_end": {
                    "type": "string",
                    "example": "2026-06-30"
                },
                "period_start": {
                    "type": "string",
                    "example": "2026-06-24"
                },
                "report_type": {
                    "type": "string",
                    "example": "weekly"
                },
                "send": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "github_com_StephenQiu30_hotkey-server_internal_model_dto.EmailRegisterRequest": {
            "type": "object",
            "required": [
                "display_name",
                "password",
                "verification_ticket"
            ],
            "properties": {
                "display_name": {
                    "type": "string",
                    "maxLength": 80
                },
                "password": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 8
                },
                "verification_ticket": {
                    "type": "string"
                }
            }
        },
        "github_com_StephenQiu30_hotkey-server_internal_model_dto.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "Passw0rd!"
                }
            }
        },
        "github_com_StephenQiu30_hotkey-server_internal_model_dto.PasswordResetRequest": {
            "type": "object",
            "required": [
                "new_password",
                "reset_token"
            ],
            "properties": {
                "new_password": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 8
                },
                "reset_token": {
                    "type": "string"
                }
            }
        },
        "github_com_StephenQiu30_hotkey-server_internal_model_dto.Report": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "hotspot_count": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "period_end": {
                    "type": "string"
                },
                "period_start": {
                    "type": "string"
                },
                "report_type": {
                    "type": "string"
                },
                "sent_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_StephenQiu30_hotkey-server_internal_model_dto.UpdateMonitorRequest": {
            "type": "object",
            "properties": {
                "alert_enabled": {
                    "type": "boolean",
                    "example": true
                },
                "language": {
                    "type": "string",
                    "example": "en"
                },
                "name": {
                    "type": "string",
                    "example": "AI monitor"
                },
                "poll_interval_minutes": {
                    "type": "integer",
                    "example": 15
                },
                "query_text": {
                    "type": "string",
                    "example": "openai OR gpt"
                },
                "region": {
                    "type": "string",
                    "example": "US"
                },
                "status": {
                    "type": "string",
                    "example": "active"
                }
            }
        },
        "github_com_StephenQiu30_hotkey-server_internal_model_dto.VerificationConfirmRequest": {
            "type": "object",
            "required": [
                "code",
                "email",
                "purpose"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "purpose": {
                    "type": "string",
                    "enum": [
                        "register",
                        "reset_password"
                    ]
                }
            }
        },
        "github_com_StephenQiu30_hotkey-server_internal_model_dto.VerificationSendRequest": {
            "type": "object",
            "required": [
                "email",
                "purpose"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "purpose": {
                    "type": "string",
                    "enum": [
                        "register",
                        "reset_password"
                    ]
                }
            }
        },
        "github_com_StephenQiu30_hotkey-server_internal_model_vo.AuthTokenData": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                }
            }
        },
        "github_com_StephenQiu30_hotkey-server_internal_model_vo.AuthenticatedUserData": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "email_verified_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "plan_type": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_StephenQiu30_hotkey-server_internal_model_vo.HealthBody": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_StephenQiu30_hotkey-server_internal_model_vo.LoginData": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_model_vo.UserData"
                }
            }
        },
        "github_com_StephenQiu30_hotkey-server_internal_model_vo.MarkNotificationReadData": {
            "type": "object",
            "properties": {
                "read": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_StephenQiu30_hotkey-server_internal_model_vo.MonitorData": {
            "type": "object",
            "properties": {
                "alert_enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "language": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "poll_interval_minutes": {
                    "type": "integer"
                },
                "query_text": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_StephenQiu30_hotkey-server_internal_model_vo.NotificationData": {
            "type": "object",
            "properties": {
                "alert_id": {
                    "type": "integer"
                },
                "channel": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "delivery_status": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "read_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_StephenQiu30_hotkey-server_internal_model_vo.UserData": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "github_com_StephenQiu30_hotkey-server_internal_platform_http.ErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_StephenQiu30_hotkey-server_internal_service.PostBrief": {
            "type": "object",
            "properties": {
                "heat": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "platform": {
                    "type": "string"
                },
                "seen_at": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "github_com_StephenQiu30_hotkey-server_internal_service.TopicSummary": {
            "type": "object",
            "properties": {
                "current_heat": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "post_count": {
                    "type": "integer"
                },
                "summary": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "trend_direction": {
                    "type": "string"
                }
            }
        },
        "github_com_StephenQiu30_hotkey-server_internal_service.TrendPoint": {
            "type": "object",
            "properties": {
                "heat_score": {
                    "type": "number"
                },
                "time": {
                    "type": "string"
                },
                "trend_direction": {
                    "type": "string"
                },
                "trend_velocity": {
                    "type": "number"
                }
            }
        },
        "internal_controller.AuthTokenResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_model_vo.AuthTokenData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_controller.AuthenticatedUserResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_model_vo.AuthenticatedUserData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_controller.EventPlatformItem": {
            "type": "object",
            "properties": {
                "heat": {
                    "type": "number"
                },
                "platform": {
                    "type": "string"
                },
                "rank": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "internal_controller.HealthResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_model_vo.HealthBody"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_controller.HotEventDetail": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "first_seen_at": {
                    "type": "string"
                },
                "heat_score": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "last_seen_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "platforms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_controller.EventPlatformItem"
                    }
                },
                "status": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "trend": {
                    "type": "string"
                }
            }
        },
        "internal_controller.HotEventItem": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "heat_score": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "trend": {
                    "type": "string"
                }
            }
        },
        "internal_controller.HotEventListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_controller.HotEventItem"
                    }
                },
                "message": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/internal_controller.HotEventMeta"
                }
            }
        },
        "internal_controller.HotEventMeta": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_controller.HotEventPostsResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_service.PostBrief"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_controller.HotEventResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/internal_controller.HotEventDetail"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_controller.LoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_model_vo.LoginData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_controller.MarkNotificationReadResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_model_vo.MarkNotificationReadData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_controller.MonitorListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_model_vo.MonitorData"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_controller.MonitorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_model_vo.MonitorData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_controller.NotificationListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_model_vo.NotificationData"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_controller.PostListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_content.PostSummary"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_controller.ReportListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_model_dto.Report"
                    }
                },
                "message": {
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_controller.ReportResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_model_dto.Report"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_controller.TopicListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_service.TopicSummary"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_controller.TrendListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_StephenQiu30_hotkey-server_internal_service.TrendPoint"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_controller.TrendingItem": {
            "type": "object",
            "properties": {
                "heat": {
                    "type": "number"
                },
                "platform": {
                    "type": "string"
                },
                "rank": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "internal_controller.TrendingListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_controller.TrendingItem"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_controller.VerificationSendResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object",
                    "properties": {
                        "email": {
                            "type": "string"
                        }
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_controller.VerificationTicketResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object",
                    "properties": {
                        "ticket": {
                            "type": "string"
                        }
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "HotKey API",
	Description:      "HotKey 热点监控平台后端 API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
